/* =====================================================================
   Dicionário português -> chinês simplificado (简体中文).

   NÃO EDITE À MÃO sem saber o que está fazendo: a chave é o texto
   português EXATAMENTE como ele aparece no HTML, e é assim que o
   js/idioma.js o encontra em tempo de execução.

   As siglas legais brasileiras (ASO, PCMSO, PGR, NR-35...) ficam em
   latim, com a explicação em chinês entre parênteses na primeira vez
   que aparecem num texto longo. Traduzi-las seria inventar termos que
   não existem em documento nenhum, e é justamente por essas siglas que
   um auditor procura.
   ===================================================================== */
window.CMH_ZH = {
 "(71) 3493-7220 · Comercial (71) 99301-0103": "(71) 3493-7220 · 商务 (71) 99301-0103",
 "(71) 90000-0000": "(71) 90000-0000",
 "(estresse, sobrecarga) entre os fatores a gerenciar — a saúde mental no trabalho também é responsabilidade da empresa.": "（压力、超负荷）纳入需要管理的因素——职场心理健康同样是企业的责任。",
 "(opcional)": "（选填）",
 "*campos obrigatórios": "*为必填项",
 ", a sua empresa é obrigada a transmitir eventos específicos dentro de prazos legais — e cada atraso ou inconsistência pode gerar": "模块中，贵公司必须在法定期限内报送特定事件——任何延迟或数据不一致都可能导致",
 ", acompanhando gestações, cuidando da saúde da mulher e ajudando a trazer ao mundo incontáveis famílias. Foi também diretor do": "，陪伴无数孕产过程，守护女性健康，帮助无数家庭迎接新生命。他还曾担任",
 ", aos 62 anos, o Dr. José Carlos partiu, vítima da Covid-19. Deixou saudade e, acima de tudo, um exemplo de dedicação, competência e amor às pessoas que atravessa gerações.": "，José Carlos医生因新冠肺炎不幸离世，享年62岁。他留下的不只是思念，更是一份跨越世代的奉献、专业与关爱他人的典范。",
 ", avaliam se a pessoa está apta para a função que vai exercer, considerando os riscos do cargo. É neste momento que se emite o primeiro ASO (Atestado de Saúde Ocupacional).": "用于评估该人员在考虑岗位风险的前提下是否适合将要从事的工作。首份ASO（职业健康证明）正是在这个时候出具的。",
 ", com respaldo técnico e conformidade legal.": "，具备技术依据并符合法律规定。",
 ", em 1984. Ao longo de quase quatro décadas dedicadas à profissão, atuou como": "医学专业，于1984年毕业。在近四十年的从医生涯中，他一直担任",
 ", informando contrato, região, tipo de exame, data e quantas pessoas vão comparecer.": "，并注明合同、地区、体检类型、日期以及参加人数。",
 ", no Centro de Camaçari - BA, em um ponto de fácil acesso e próximo às principais vias da cidade. Nossa estrutura foi pensada para receber você e a sua família com todo o conforto e comodidade, desde a chegada.": "，位于巴伊亚州Camaçari市中心，交通便利，紧邻城市主要干道。我们的场所经过精心设计，从您踏入的那一刻起，就为您和家人提供充分的舒适与便利。",
 ", onde exerceu quatro mandatos como vereador e presidiu a Câmara Municipal por duas vezes, sempre comprometido com a saúde e o bem-estar da comunidade.": "，他在那里连任四届市议员，并两度担任市议会议长，始终致力于社区的健康与福祉。",
 ", preparados para oferecer a melhor experiência e os melhores resultados em cada atendimento, do consultório ao ambiente de trabalho.": "，致力于在从诊室到工作场所的每一次服务中，提供最好的体验和最好的结果。",
 ", previsto na NR-7, planeja e organiza todas as ações de saúde dos trabalhadores, definindo quais exames são necessários conforme os riscos de cada função.": "依据NR-7的规定，规划和组织所有劳动者健康管理措施，并根据每个岗位的风险确定需要开展哪些检查项目。",
 ", previsto na NR-7, é o programa que planeja e organiza as ações de saúde dos trabalhadores. Ele define quais exames são necessários de acordo com os riscos de cada função e acompanha a saúde da equipe ao longo do tempo, de forma integrada ao gerenciamento de riscos da empresa.": "是依据NR-7制定的方案，用于规划和组织劳动者的健康管理措施。它根据各岗位的风险确定需要开展哪些体检项目，并长期跟踪团队的健康状况，与企业的风险管理相互衔接。",
 ", referência na região.": "，该院是本地区的标杆机构。",
 ". Foi dele a visão de um lugar onde a ciência caminhasse ao lado da sensibilidade, e onde cada pessoa fosse cuidada com atenção, respeito e carinho. É esse legado que dá nome e alma à nossa clínica.": "。正是他描绘了这样一个愿景：让科学与人文关怀并行，让每一个人都得到用心、尊重和关爱的照护。正是这份传承赋予了我们诊所名字与灵魂。",
 "000.000.000-00": "000.000.000-00",
 "06 Ago 2026": "2026年8月6日",
 "07 Ago 2026": "2026年8月7日",
 "1 Jul 2026": "2026年7月1日",
 "1. Quais dados coletamos": "1. 我们收集哪些数据",
 "10 Jul 2026": "2026年7月10日",
 "12 Jun 2026": "2026年6月12日",
 "15 Jul 2026": "2026年7月15日",
 "15 de março de 2021": "2021年3月15日",
 "16 Jul 2026": "2026年7月16日",
 "18 Jul 2026": "2026年7月18日",
 "2. Como utilizamos os seus dados": "2. 我们如何使用您的数据",
 "20 Jul 2026": "2026年7月20日",
 "26 Jun 2026": "2026年6月26日",
 "3. Compartilhamento de dados": "3. 数据共享",
 "4,1 milhões de trabalhadores": "410万名劳动者",
 "4. Segurança das informações": "4. 信息安全",
 "5. Seus direitos como titular": "5. 您作为数据主体的权利",
 "546 mil afastamentos": "54.6万例病休",
 "6. Cookies": "6. Cookie",
 "7. Retenção dos dados": "7. 数据保存期限",
 "8 Jul 2026": "2026年7月8日",
 "8. Contato": "8. 联系方式",
 "A Clínica": "关于诊所",
 "A Clínica Medicina Humana": "Clínica Medicina Humana",
 "A Clínica Medicina Humana ajuda a sua empresa a incluir os riscos psicossociais no programa de saúde ocupacional, com avaliação técnica e programas personalizados.": "Medicina Humana诊所帮助贵公司将社会心理风险纳入职业健康计划，提供技术评估和定制化方案。",
 "A Clínica Medicina Humana apoia a sua empresa na adequação às NRs e no gerenciamento de riscos ocupacionais. Fale conosco: (71) 3493-7220.": "Clínica Medicina Humana协助贵公司符合各项NR要求并做好职业风险管理。欢迎联系我们：(71) 3493-7220。",
 "A Clínica Medicina Humana cuida do PCMSO, dos exames periódicos e do acompanhamento da sua equipe, com estrutura própria de exames laboratoriais e de imagem.": "Clínica Medicina Humana负责贵公司的PCMSO、定期体检和团队健康跟踪，并拥有自有的检验和影像检查设施。",
 "A Clínica Medicina Humana está localizada na": "Medicina Humana诊所位于",
 "A Clínica Medicina Humana oferece serviços de medicina ocupacional para empresas de todos os portes. Fale conosco pelo telefone (71) 3493-7220 e mantenha a sua empresa em conformidade.": "Medicina Humana诊所为各种规模的企业提供职业医学服务。请拨打电话 (71) 3493-7220 联系我们，让贵公司保持合规。",
 "A Clínica Medicina Humana realiza avaliações ergonômicas e programas de saúde ocupacional que ajudam a sua empresa a prevenir lesões e a cumprir a NR-17.": "Clínica Medicina Humana提供人体工效学评估和职业健康方案，帮助贵公司预防损伤并符合NR-17的要求。",
 "A Clínica Medicina Humana realiza exames ocupacionais e cuida do PCMSO e do ASO da sua empresa, com agilidade e segurança técnica. Fale conosco: (71) 3493-7220.": "Medicina Humana诊所提供职业体检服务，并负责贵公司的PCMSO和ASO，高效且具备技术保障。联系我们：(71) 3493-7220。",
 "A Clínica Medicina Humana realiza os exames admissionais, periódicos, de retorno ao trabalho, de mudança de risco e demissionais, emite o ASO e organiza os dados para o envio dos eventos de SST. Sua empresa pode": "Clínica Medicina Humana提供入职、定期、复工、风险变更和离职体检，出具ASO，并整理数据以便报送SST事件。贵公司可以",
 "A Clínica Medicina Humana respeita a sua privacidade e está comprometida com a proteção dos seus dados pessoais. Esta política explica, de forma transparente, como coletamos, usamos, armazenamos e protegemos as suas informações, em conformidade com a Lei Geral de Proteção de Dados (Lei nº 13.709/2018 — LGPD).": "Medicina Humana诊所尊重您的隐私，并致力于保护您的个人数据。本政策以透明的方式说明我们如何收集、使用、存储和保护您的信息，符合《通用数据保护法》（第13.709/2018号法律——LGPD）的规定。",
 "A Medicina Humana nasceu do sonho e da dedicação do Dr. José Carlos Prado Correia. Ginecologista e obstetra por quase quatro décadas, ele acreditava que cuidar de pessoas é, antes de tudo, um ato de humanidade. É o seu legado que a nossa clínica honra todos os dias.": "Medicina Humana源自José Carlos Prado Correia医生的梦想与付出。作为从业近四十年的妇产科医生，他始终相信，照护他人首先是一种人道之举。我们诊所每天都在传承他留下的这份精神。",
 "A NR-1 define as diretrizes básicas de segurança e saúde no trabalho e as responsabilidades de empregadores e trabalhadores. Foi ela que introduziu, de forma estruturada, o conceito de Gerenciamento de Riscos Ocupacionais — uma abordagem contínua para identificar, avaliar e controlar os riscos do ambiente laboral.": "NR-1规定了职业安全与健康的基本准则以及雇主和劳动者的责任。正是这项标准系统性地引入了职业风险管理的概念——一种持续识别、评估和控制工作环境风险的方法。",
 "A NR-1 estabelece o": "NR-1确立了",
 "A NR-1 é a Norma Regulamentadora que estabelece as disposições gerais de segurança e saúde no trabalho e organiza o Gerenciamento de Riscos Ocupacionais (GRO). Entender essas regras é essencial para manter a empresa em conformidade e proteger os trabalhadores.": "NR-1是规定职业安全与健康一般条款、并搭建职业风险管理（GRO）体系的监管条例。理解这些规则，对企业保持合规和保护劳动者都至关重要。",
 "A NR-17 estabelece parâmetros para adaptar as condições de trabalho às características das pessoas, considerando mobiliário, postura, iluminação, ritmo e organização das tarefas. A Análise Ergonômica do Trabalho (AET) é a ferramenta que identifica os pontos de risco.": "NR-17规定了将工作条件适配于人员特征的各项参数，涵盖办公家具、姿势、照明、节奏和任务组织。工作工效学分析（AET）正是识别风险点的工具。",
 "A Ouvidoria é o seu canal de comunicação direta com a clínica para o registro de reclamações, sugestões e elogios. Sua opinião nos ajuda a melhorar a cada dia.": "意见受理中心是您与诊所直接沟通的渠道，可用于提交投诉、建议和表扬。您的意见帮助我们每天不断进步。",
 "A Portaria MTE nº 1.131/2025 atualizou os valores das multas por descumprimento das obrigações de SST, que podem chegar a": "MTE（巴西劳动和就业部）第1.131/2025号部令更新了违反SST义务的罚款金额，最高可达",
 "A atualização das Normas Regulamentadoras trouxe para o centro do debate um tema que muitas empresas ainda tratavam como secundário: a saúde mental dos trabalhadores. Agora, identificar e gerenciar os riscos psicossociais passa a fazer parte da gestão de segurança e saúde no trabalho.": "监管条例（NR）的更新，把许多企业此前仍视为次要的议题推到了讨论中心：劳动者的心理健康。如今，识别和管理社会心理风险已成为职业安全与健康管理的一部分。",
 "A automedicação ou o uso apenas estético, sem indicação, pode ser perigoso.": "自行用药，或在没有医学指征的情况下仅出于美观目的使用，可能存在危险。",
 "A carga horária e o conteúdo seguem o que cada Norma exige e a\n           atividade que a sua equipe realmente executa.": "课时和内容依据各项条例的要求以及贵公司团队实际从事的作业来安排。",
 "A clínica": "关于诊所",
 "A empresa contrata": "企业下单",
 "A fiscalização ficou automática": "监管检查已经自动化",
 "A hipertensão arterial é uma das doenças crônicas mais comuns e, ao mesmo tempo, uma das mais silenciosas. Muitas pessoas convivem com a pressão elevada por anos sem sentir nada, até que surja uma complicação séria.": "高血压是最常见的慢性病之一，同时也是最“沉默”的疾病之一。许多人血压偏高多年却毫无感觉，直到出现严重并发症。",
 "A medicina ocupacional, também chamada de medicina do trabalho, cuida da relação entre a atividade profissional e a saúde do trabalhador. Ela atua na prevenção, no acompanhamento e no controle de doenças e riscos relacionados ao ambiente de trabalho, por meio de exames, programas e laudos técnicos.": "职业医学，也称劳动医学，关注职业活动与劳动者健康之间的关系。它通过体检、专项计划和技术报告，对与工作环境相关的疾病和风险进行预防、随访和控制。",
 "A pressão alta força o coração e danifica as artérias ao longo do tempo. Sem controle, aumenta o risco de infarto, AVC, insuficiência cardíaca e problemas nos rins e na visão. Como não costuma dar sintomas, muitas vezes só é descoberta em uma medição de rotina.": "高血压会加重心脏负担，并随着时间推移损伤动脉。若不加以控制，会增加心肌梗死、脑卒中、心力衰竭以及肾脏和视力问题的风险。由于通常没有症状，很多时候只能在常规测量中被发现。",
 "ASO (Atestado de Saúde Ocupacional)": "ASO（职业健康证明）",
 "ASO e PCMSO": "ASO与PCMSO",
 "ASO e PCMSO — Clínica Medicina Humana": "ASO与PCMSO — Medicina Humana诊所",
 "ASO e PCMSO: os exames ocupacionais obrigatórios e as responsabilidades da empresa.": "ASO与PCMSO：强制性职业健康体检以及企业的责任。",
 "ASO e PCMSO: os exames ocupacionais que a sua empresa não pode ignorar": "ASO与PCMSO：贵公司不能忽视的职业健康体检",
 "ASO emitido corretamente, mas nunca transmitido ao eSocial;": "ASO已正确出具，却从未上报eSocial；",
 "Abrir menu": "打开菜单",
 "Acessar meus exames": "查看我的检查",
 "Acessar Área Médica": "进入医师专区",
 "Acessar →": "进入 →",
 "Acesse com segurança os seus resultados de exames da Clínica Medicina Humana.": "安全查看您在Medicina Humana诊所的检查结果。",
 "Acesse os seus resultados com segurança, a qualquer hora e de qualquer lugar.": "随时随地安全查看您的检查结果。",
 "Acesse seus resultados": "查看您的检查结果",
 "Acesso exclusivo para os médicos parceiros da clínica.": "仅限诊所合作医师使用。",
 "Acompanhamento e encerramento de contrato": "在职跟踪与合同终止",
 "Acompanhe nossas redes sociais": "关注我们的社交媒体",
 "Administrativo": "行政",
 "Administração": "后台管理",
 "Admissional": "入职体检",
 "Admissional:": "入职体检：",
 "Adotamos medidas técnicas e administrativas para proteger os seus dados contra acessos não autorizados, perda, alteração ou divulgação indevida. O acesso às informações é restrito a profissionais autorizados e sujeitos a deveres de confidencialidade.": "我们采取技术和管理措施，保护您的数据免遭未经授权的访问、丢失、篡改或不当披露。信息的访问权限仅限于经授权并负有保密义务的专业人员。",
 "Afastamentos batem recorde no INSS e o exame periódico vira prioridade": "INSS病假人数创纪录，定期体检成为优先事项",
 "Afastamentos batem recorde no INSS e o exame periódico vira prioridade — Clínica Medicina Humana": "INSS病假人数创纪录，定期体检成为优先事项 — Medicina Humana诊所",
 "Afastamentos por doença bateram recorde em 2025. Entenda por que o exame periódico é a forma mais barata de a empresa se proteger.": "2025年因病休假人数创下新高。了解为什么定期体检是企业保护自己成本最低的方式。",
 "Afastamentos, acidentes e queda de produtividade": "病假、事故和生产力下降",
 "Agendar pelo WhatsApp": "通过WhatsApp预约",
 "Agendar →": "预约 →",
 "Agende agora": "立即预约",
 "Agende os exames da sua equipe pelo site": "通过网站预约团队体检",
 "Agende os exames ocupacionais da sua empresa na Clínica Medicina Humana. Atendimento em Salvador, Camaçari e Candeias.": "在Clínica Medicina Humana预约贵公司的职业健康体检。服务范围覆盖Salvador、Camaçari和Candeias。",
 "Agende por WhatsApp": "通过WhatsApp预约",
 "Agende seu exame": "预约您的检查",
 "Agende seu exame — Clínica Medicina Humana": "预约体检 — Clínica Medicina Humana",
 "Agende seus exames": "预约您的检查项目",
 "Agende seus exames ocupacionais": "预约您的职业体检",
 "Agende sua consulta": "预约就诊",
 "Agende sua consulta pelo WhatsApp": "通过WhatsApp预约就诊",
 "Agilidade e tudo em um só lugar": "高效快捷，一站式服务",
 "Aguarde, estamos abrindo a Área Médica.": "请稍候，正在打开医疗专区。",
 "Aguarde, estamos abrindo o sistema de exames.": "请稍候，正在打开检查系统。",
 "Ajustar cadeira, mesa e a altura da tela para cada trabalhador;": "为每位劳动者调整座椅、桌子和屏幕高度；",
 "Alimentação equilibrada e atividade física continuam sendo a base do tratamento;": "均衡饮食和体育锻炼仍然是治疗的基础；",
 "Além da avaliação clínica, podem ser solicitados exames complementares conforme a atividade — como audiometria, exames laboratoriais ou avaliações direcionadas aos riscos identificados.": "除临床评估外，还可能根据作业内容要求进行补充检查——例如听力测定、实验室检验，或针对已识别风险的专项评估。",
 "Além da conformidade, uma equipe que trata os seus colaboradores com atenção.": "不只是合规，更是一支用心对待贵公司员工的团队。",
 "Além de cumprir a legislação, manter os exames e programas em ordem protege a empresa de autuações, reduz afastamentos e demonstra cuidado real com as pessoas. Exames complementares — como audiometria, exames de sangue ou avaliações específicas — podem ser exigidos conforme os riscos da atividade.": "除了遵守法律之外，把体检和各项方案维持在规范状态，还能使企业免于行政处罚、减少病休，并体现出对员工的真正关怀。根据作业风险的不同，可能还需要进行补充检查——例如听力测定、血液检验或专项评估。",
 "Além de ser uma obrigação prevista na CLT e nas Normas Regulamentadoras (NRs) do Ministério do Trabalho, o serviço traz benefícios diretos ao negócio:": "除了是CLT（巴西劳动法）和劳动部各项规范标准（NRs）规定的义务之外，该服务还为企业带来直接的效益：",
 "Além do rastreamento, hábitos de vida fazem diferença: alimentação rica em fibras, frutas e vegetais, redução de carnes processadas, prática regular de atividade física, controle do peso, moderação no álcool e não fumar.": "除筛查之外，生活习惯同样重要：多摄入富含膳食纤维的食物、水果和蔬菜，减少加工肉类，坚持规律运动，控制体重，限制饮酒，不吸烟。",
 "Ambiente humano": "有温度的环境",
 "Ambientes mal adaptados levam a lesões por esforço repetitivo (LER/DORT), fadiga, afastamentos e perda de produtividade. Além do custo humano, há o impacto financeiro e legal para a empresa.": "不合适的工作环境会导致重复性劳损（LER/DORT）、疲劳、病休和生产力下降。除了人的代价之外，企业还要承担财务和法律层面的影响。",
 "Ambientes que ignoram esses fatores tendem a registrar mais afastamentos, absenteísmo, rotatividade e queda de produtividade. Transtornos como ansiedade e depressão estão entre as principais causas de afastamento do trabalho no país. Cuidar da saúde mental deixou de ser um diferencial e passou a ser uma responsabilidade.": "忽视这些因素的工作环境，往往会出现更多的病休、缺勤、人员流失和生产力下降。焦虑和抑郁等障碍已是巴西职工病休的主要原因之一。关注心理健康不再是加分项，而是一项责任。",
 "Aptidão antes do início das atividades": "上岗前的适任评估",
 "Arquivo (PDF/imagem)": "文件（PDF/图片）",
 "Assumimos toda a gestão da saúde ocupacional da sua empresa com rigor técnico, prazos cumpridos e um atendimento próximo. Você foca no seu negócio com a tranquilidade de estar sempre em conformidade.": "我们以严谨的技术标准、准时的交付和贴心的服务，全面承接贵公司的职业健康管理。您可以专注于自身业务，安心保持始终合规。",
 "Assunto*": "主题*",
 "Atendimento": "就诊服务",
 "Atendimento para empresas por telefone ou WhatsApp.": "通过电话或WhatsApp为企业提供服务。",
 "Atestado e programa de controle médico": "健康证明与医学监护计划",
 "Atualizado em julho de 2026": "更新于2026年7月",
 "Aulas e vídeos | Administração": "课时与视频 | 后台管理",
 "Ação": "操作",
 "Baixar PDF": "下载PDF",
 "Bem-estar · 12 de junho de 2026": "健康生活 · 2026年6月12日",
 "Bem-vindos": "欢迎",
 "Boas práticas": "良好做法",
 "Buscar especialidade": "查找专科",
 "Buscar exame": "查找检查项目",
 "Buscar exame (ex.: hemograma, ultrassom, ECG)": "搜索检查项目（例如：血常规、超声、心电图）",
 "Buscar por exame ou paciente...": "按检查项目或患者搜索……",
 "Buscar por nome ou CPF...": "按姓名或CPF搜索…",
 "Buscar...": "搜索……",
 "CNPJ* (apenas números)": "CNPJ*（仅填数字）",
 "CPF": "CPF",
 "CPF do paciente": "患者CPF",
 "CPF*": "CPF*",
 "CRM": "CRM",
 "CRM do médico (opcional)": "医师CRM编号（选填）",
 "Cada certificado sai com o nome e o CPF do trabalhador, como a\n            Norma exige. Certificado sem dono não vale numa fiscalização.": "每张证书都按条例要求载明劳动者的姓名和CPF。没有具体持有人的证书在监督检查中是无效的。",
 "Cada um faz o seu": "各自完成自己的课程",
 "Cadastrar e gerar senha": "注册并生成密码",
 "Cadastro": "注册",
 "Camaçari": "Camaçari",
 "Cancelar": "取消",
 "Candeias": "Candeias",
 "Capacitar líderes para reconhecer sinais de sofrimento;": "培训管理者识别员工的心理困扰信号；",
 "Capacitação da sua equipe nas Normas Regulamentadoras, com certificado.": "为贵公司团队提供监管条例（NR）培训，并颁发证书。",
 "Capacitação em Normas Regulamentadoras para a sua equipe, com instrutores qualificados, certificado e conteúdo alinhado à realidade da sua operação.": "为您的团队提供规范标准（NR）培训，配备资深讲师、颁发证书，内容贴合贵公司实际运营情况。",
 "Capacitação nas Normas Regulamentadoras com instrutores qualificados,\n         prova ao final e certificado no nome de cada trabalhador. A empresa\n         recebe um código; cada pessoa faz no seu tempo.": "由具备资质的讲师开展监管条例（NR）培训，课程结束后进行考试，并颁发载有每位劳动者姓名的证书。企业获得一个代码；每个人可按自己的时间学习。",
 "Carregando a Área Médica…": "正在加载医师专区…",
 "Carregando seu acesso ao exame…": "正在加载您的检查访问权限……",
 "Carregando...": "加载中……",
 "Carregando…": "加载中…",
 "Central de Notícias": "资讯中心",
 "Central de Notícias da Clínica Medicina Humana — saúde, prevenção e medicina ocupacional.": "Clínica Medicina Humana资讯中心 — 健康、预防与职业健康医学。",
 "Central de Notícias — Clínica Medicina Humana": "资讯中心 — Medicina Humana诊所",
 "Centro de Diagnóstico": "诊断中心",
 "Certificado": "证书",
 "Certificado autêntico, conferido na hora": "证书真实有效，即时核验",
 "Certificado no nome dele": "以本人姓名签发证书",
 "Certificado | Clínica Medicina Humana": "证书 | Clínica Medicina Humana",
 "Clique aqui": "点击这里",
 "Clique num curso para ver as aulas dele e subir os vídeos.": "点击某个课程即可查看其课时并上传视频。",
 "Clínica Medicina Humana": "Medicina Humana诊所",
 "Clínica Medicina Humana — Cuidar de você é a nossa vocação": "Medicina Humana诊所——关爱您是我们的使命",
 "Clínica Medicina Humana — cuidado completo, tecnologia avançada e equipe qualificada para você e sua família.": "Medicina Humana诊所——为您和家人提供全方位照护、先进技术和专业团队。",
 "Colonoscopia:": "结肠镜检查：",
 "Com a inclusão obrigatória dos riscos psicossociais no PGR, esse cruzamento deixou de ser apenas recomendável: os dados do programa de riscos precisam alimentar o PCMSO para que o médico do trabalho leia o exame no contexto real da função.": "随着社会心理风险被强制纳入PGR，这种数据比对不再只是建议：风险管理计划的数据必须导入PCMSO，让职业医师能够结合岗位的真实情况来解读体检结果。",
 "Com carga horária e validade": "含课时与有效期",
 "Comercial:": "商务：",
 "Comercial: (71) 99301-0103": "商务联系：(71) 99301-0103",
 "Como Chegar": "交通指引",
 "Como Chegar — Clínica Medicina Humana": "交通指引 — Medicina Humana诊所",
 "Como Chegar — Clínica Medicina Humana, Centro de Camaçari - BA.": "交通指引 — Medicina Humana诊所，巴伊亚州Camaçari市中心。",
 "Como funciona": "使用流程",
 "Como gerenciar na prática": "实际操作中如何管理",
 "Como manter tudo em dia": "如何保持一切合规到位",
 "Como prevenir e controlar": "如何预防与控制",
 "Como se adequar": "如何做到合规",
 "Como é feito o rastreamento": "筛查怎么做",
 "Concordo com os termos e condições.": "我同意相关条款和条件。",
 "Conexão criptografada. Por segurança, você sai automaticamente após alguns minutos sem uso. Seus dados de saúde são tratados conforme a LGPD.": "加密连接。出于安全考虑，闲置几分钟后您将自动退出。您的健康数据依照LGPD处理。",
 "Conexão criptografada. Seus dados de saúde são protegidos conforme a LGPD.": "加密连接。您的健康数据依照LGPD受到保护。",
 "Conferência sem cadastro": "无需注册即可查验",
 "Confira a autenticidade de um certificado de treinamento em NR emitido pela Clínica Medicina Humana. Digite o código impresso no documento.": "验证由Clínica Medicina Humana签发的NR培训证书的真伪。请输入证书上印制的代码。",
 "Confirmar nova senha": "确认新密码",
 "Conformidade garantida": "保证合规",
 "Conhecer →": "了解详情 →",
 "Conheça a sua história →": "了解他的故事 →",
 "Consulte e baixe o Atestado de Saúde Ocupacional da sua empresa de forma rápida e segura, quando e onde precisar.": "随时随地快速、安全地查询和下载贵公司的职业健康证明（ASO）。",
 "Contar com apoio técnico especializado em saúde e segurança do trabalho.": "获得职业安全与健康方面的专业技术支持。",
 "Contato": "联系我们",
 "Contato — Clínica Medicina Humana": "联系我们 — Clínica Medicina Humana",
 "Contatos": "联系方式",
 "Conte um pouco sobre você e sua experiência": "简单介绍一下您本人和您的工作经历",
 "Contratar, acompanhar e desligar um colaborador envolve responsabilidades de saúde previstas em lei. O PCMSO e o ASO estão no centro dessas obrigações — e o descumprimento pode gerar multas e passivos trabalhistas.": "招聘、在职管理和解除劳动关系都涉及法律规定的健康责任。PCMSO（职业健康医学监控计划）和ASO（职业健康证明）正是这些义务的核心——不遵守可能导致罚款和劳动纠纷负债。",
 "Contrato*": "合同*",
 "Correlação clara entre o quadro clínico e os riscos da função;": "临床表现与岗位风险之间关联清晰；",
 "Crescimento": "成长",
 "Cresça com quem cuida de você em cada detalhe": "与在每一个细节中关爱您的团队一起成长",
 "Criar canais seguros de escuta e de denúncia;": "建立安全的倾诉和举报渠道；",
 "Criar nova senha": "创建新密码",
 "Criar uma senha nova": "创建一个新密码",
 "Crie uma nova\n              com o código da empresa": "用企业代码重新设置一个",
 "Crie uma senha": "设置密码",
 "Crie uma senha só sua. Recomendamos trocar no primeiro acesso.": "请设置一个只属于您的密码。建议首次登录后就更换。",
 "Cuidado real com as pessoas": "真正关爱每一个人",
 "Cuidados e limites": "注意事项与局限",
 "Cuidamos das pessoas e da produtividade das empresas. Da prevenção à manutenção da saúde, reunimos": "我们关爱员工，也关注企业的生产力。从预防到健康维护，我们汇聚了完善的",
 "Cuidando de você em cada detalhe": "细致入微，呵护您的健康",
 "Cuidar da iluminação e do conforto térmico;": "注意照明和温度舒适度；",
 "Cuidar da saúde de quem trabalha não é apenas uma boa prática de gestão — é uma exigência legal. A medicina ocupacional é a área que conecta saúde e trabalho, prevenindo doenças e acidentes e mantendo a empresa em conformidade com a legislação.": "关注员工的健康不仅是良好的管理实践，更是法律要求。职业医学是连接健康与工作的领域，既能预防疾病和事故，也能让企业保持合规。",
 "Cumprir obrigações legais, regulatórias e sanitárias.": "履行法律、监管和卫生方面的义务。",
 "Cursos": "课程",
 "Câncer colorretal: por que o rastreamento agora começa aos 45 anos": "结直肠癌：为什么筛查现在从45岁开始",
 "Código da empresa": "企业代码",
 "Código do certificado": "证书编码",
 "Código do cupom": "优惠码",
 "Dados clínicos divergentes entre o ASO em papel e o que foi transmitido;": "纸质ASO与已上报数据之间的临床信息不一致；",
 "Data": "日期",
 "Data dos exames": "检查日期",
 "De acordo com a LGPD, você pode, a qualquer momento, solicitar: a confirmação da existência de tratamento; o acesso, a correção ou a atualização dos seus dados; a portabilidade; a anonimização ou eliminação de dados desnecessários; e a revogação do consentimento.": "根据LGPD，您可以随时要求：确认是否存在数据处理；访问、更正或更新您的数据；数据可携；对不必要的数据进行匿名化或删除；以及撤回同意。",
 "De mudança de função:": "岗位变更体检：",
 "De retorno ao trabalho:": "复工体检：",
 "Dedicado ao próximo também fora do consultório, envolveu-se na vida pública de": "在诊室之外，他同样心系他人，积极参与",
 "Deixe a saúde ocupacional com quem entende": "把职业健康交给专业的团队",
 "Deixe o quarto escuro, silencioso e com temperatura agradável.": "保持卧室黑暗、安静，温度适宜。",
 "Demissional": "离职体检",
 "Demissional:": "离职体检：",
 "Demonstra responsabilidade social e cuidado com as pessoas.": "展现社会责任感和对员工的关怀。",
 "Descrição (opcional)": "说明（选填）",
 "Dia em que irá comparecer*": "前来就诊的日期*",
 "Diagnóstico por imagem": "影像诊断",
 "Dias d’Ávila (BA)": "Dias d’Ávila（巴伊亚州）",
 "Digite o nome do exame ou explore por categoria abrindo os grupos abaixo.": "输入检查项目名称，或展开下方分组按类别浏览。",
 "Do laboratório à imagem de alta precisão: encontre o exame que você precisa e agende com quem cuida de você em cada detalhe.": "从实验室检验到高精度影像检查：找到您需要的项目，向细致入微呵护您的团队预约。",
 "Documentação e exames corretos reduzem o risco de autuações e ações trabalhistas.": "完备的文件和规范的体检可降低被处罚和劳动诉讼的风险。",
 "Dores nas costas, no pescoço e nos punhos estão entre as queixas mais comuns de quem passa horas na mesma posição. Investir em ergonomia não é luxo: é uma forma eficaz de proteger a saúde do trabalhador e a produtividade da empresa.": "背部、颈部和手腕疼痛是长时间保持同一姿势人群最常见的不适。投入工效学并非奢侈之举：这是保护劳动者健康和企业生产力的有效方式。",
 "Dormir bem costuma ser tratado como um luxo, mas a ciência mostra que o sono é um pilar da saúde tão importante quanto a alimentação e a atividade física. Ele influencia diretamente a imunidade, o metabolismo, o humor e o coração.": "睡个好觉常被当作一种奢侈，但科学研究表明，睡眠是与饮食和运动同等重要的健康支柱。它直接影响免疫力、代谢、情绪和心脏健康。",
 "Dr. Jose Carlos Prado Correia": "Dr. Jose Carlos Prado Correia",
 "Dr. José Carlos Prado Correia": "Dr. José Carlos Prado Correia",
 "Dúvida": "咨询",
 "E-mail": "电子邮箱",
 "E-mail comercial": "商务邮箱",
 "E-mail do comercial": "商务部电子邮箱",
 "E-mail*": "电子邮箱*",
 "E-mail:": "电子邮箱：",
 "Elaborar e manter atualizado o PGR e o inventário de riscos;": "编制并持续更新PGR和风险清单；",
 "Elogio": "表扬",
 "Em": "在",
 "Emitido no nome de quem fez": "以参训者本人姓名签发",
 "Empresas conveniadas marcam os exames da equipe direto pelo site: informe o contrato, a região, o tipo de exame, a data e quantas pessoas vão comparecer.": "签约企业可直接通过网站预约团队体检：填写合同、区域、体检类型、日期以及参检人数即可。",
 "Empresas conveniadas marcam os exames da equipe pelo site.": "签约企业可通过网站预约团队体检。",
 "Empresas conveniadas: solicite o agendamento dos exames ocupacionais da sua equipe. Informe o contrato, a região de atendimento, o tipo de exame, a data e quantas pessoas vão comparecer.": "签约企业：请在此申请为团队预约职业体检。请注明合同、服务地区、体检类型、日期以及参加人数。",
 "Encontre as especialidades médicas da Clínica Medicina Humana.": "查找Clínica Medicina Humana提供的各医疗专科。",
 "Endereço": "地址",
 "Enfermagem": "护理",
 "Entenda cada serviço em detalhe": "详细了解每一项服务",
 "Entrar": "登录",
 "Entrar | Treinamentos em NRs": "登录 | NR培训",
 "Entre com o seu CPF e a senha que a clínica enviou para você.": "请输入您的CPF和诊所发送给您的密码。",
 "Entre com o seu CPF, ou use o código que a sua empresa enviou.": "请输入您的CPF，或使用贵公司发送的代码。",
 "Entre com o seu usuário e senha do SistemaCMH.": "请输入您的SistemaCMH用户名和密码。",
 "Entre em contato pelo telefone de atendimento.": "请拨打服务电话与我们联系。",
 "Entre os principais estão os exames ocupacionais (admissional, periódico, de retorno ao trabalho, de mudança de função e demissional), a emissão do ASO, o PCMSO, laudos, avaliações de risco e o apoio às exigências das NRs. Contar com uma clínica especializada garante que tudo seja feito com segurança técnica e dentro dos prazos legais.": "其中主要包括职业体检（入职、定期、复工、岗位变更和离职体检）、ASO（职业健康证明）的出具、PCMSO、各类技术报告、风险评估以及对各项NR要求的支持。选择专业诊所可确保所有工作都具备技术保障并在法定期限内完成。",
 "Enviar": "发送",
 "Enviar candidatura": "提交应聘申请",
 "Enviar informações, lembretes e resultados de exames, quando aplicável;": "在适用的情况下发送信息、提醒和检查结果；",
 "Enviar o exame ocupacional deixou de ser tarefa de bastidor. Com o eSocial cruzando dados em tempo real, um periódico atrasado aparece sozinho no sistema — sem visita de auditor e sem aviso prévio.": "上报职业体检结果不再是幕后工作。随着eSocial实时比对数据，一份逾期的定期体检会自动在系统中显现——无需稽查员上门，也没有事先通知。",
 "Envie o seu currículo": "投递您的简历",
 "Envie seu currículo": "投递您的简历",
 "Envie seu currículo em PDF para o nosso RH.": "请将您的PDF格式简历发送给我们的人力资源部。",
 "Envie-nos uma mensagem e diga como podemos te ajudar": "给我们留言，告诉我们能为您做些什么",
 "Equipe": "团队",
 "Ergonomia no trabalho: como prevenir lesões e reduzir afastamentos": "职场工效学：如何预防损伤、减少病假",
 "Ergonomia no trabalho: como prevenir lesões e reduzir afastamentos — Clinica Medicina Humana": "职场人体工效学：如何预防损伤、减少病休 — Clinica Medicina Humana",
 "Escolha o assunto*": "请选择主题*",
 "Escolha um módulo para começar.": "请选择一个模块开始学习。",
 "Escreva aqui a sua mensagem*": "请在此写下您的留言*",
 "Especialidade": "专科",
 "Especialidades": "专科门诊",
 "Especialidades — Clínica Medicina Humana": "专科门诊 — Clínica Medicina Humana",
 "Esqueceu a senha?": "忘记密码？",
 "Esqueci minha senha": "忘记密码",
 "Esta política pode ser atualizada periodicamente. Recomendamos que você a consulte com regularidade para se manter informado sobre como protegemos os seus dados.": "本政策可能会定期更新。建议您经常查阅，以便及时了解我们如何保护您的数据。",
 "Estamos de volta": "我们回来了",
 "Este conteúdo tem caráter informativo e educativo e não substitui a consulta com um profissional de saúde. A Clínica Medicina Humana pode ajudar você a cuidar do seu sono e da sua saúde.": "本内容仅供参考和科普之用，不能替代专业医务人员的诊疗。Clínica Medicina Humana可以帮助您照顾好自己的睡眠和健康。",
 "Este conteúdo tem caráter informativo e educativo e não substitui a consulta com um profissional de saúde. Agende uma avaliação na Clínica Medicina Humana para saber quando iniciar o seu rastreamento.": "本内容仅供参考和科普，不能替代健康专业人员的诊疗。请前往Medicina Humana诊所预约评估，了解您应何时开始筛查。",
 "Este conteúdo tem caráter informativo e educativo e não substitui a consulta com um profissional de saúde. Procure a Clínica Medicina Humana para uma avaliação individualizada.": "本内容仅供参考和科普之用，不能替代专业医务人员的诊疗。请前往Clínica Medicina Humana接受个性化评估。",
 "Estou na clínica": "我在诊所内",
 "Estrutura moderna": "现代化的设施",
 "Estudos indicam que a privação de sono está associada a maior suscetibilidade a infecções e a uma resposta mais fraca — inclusive a vacinas. Além disso, dormir pouco de forma crônica se relaciona a maior risco de obesidade, diabetes tipo 2, hipertensão e alterações de humor, como ansiedade e depressão.": "研究表明，睡眠不足与更易受到感染以及免疫应答减弱有关——包括对疫苗的应答。此外，长期睡眠不足还与肥胖、2型糖尿病、高血压以及焦虑、抑郁等情绪障碍的风险升高相关。",
 "Eventos de SST entregues corretamente e dentro dos prazos exigidos.": "SST事件在规定期限内正确提交。",
 "Eventos de segurança e saúde no trabalho · saiba mais →": "职业安全与健康事件报送 · 了解更多 →",
 "Evite cafeína e álcool no fim do dia;": "临近傍晚避免摄入咖啡因和酒精；",
 "Ex.: 5": "例如：5",
 "Ex.: CRM/BA 43699": "例：CRM/BA 43699",
 "Ex.: Cardiologia": "例如：心脏内科",
 "Ex.: Exames laboratoriais, imagem...": "例：实验室检验、影像检查…",
 "Exame": "检查项目",
 "Exames": "检查项目",
 "Exames admissionais": "入职体检",
 "Exames laboratoriais e de imagem reunidos em um só lugar, com agilidade nos resultados e todo o conforto que você merece.": "检验与影像检查汇聚于一处，出结果快捷，让您享有应得的舒适体验。",
 "Exames laboratoriais, de imagem, cardiológicos e mais na Clínica Medicina Humana. Encontre o exame que você precisa e agende com facilidade.": "在Medicina Humana诊所可进行检验、影像、心脏等各类检查。找到您需要的检查项目，轻松预约。",
 "Exames ocupacionais fora do prazo no eSocial expõem a empresa a autuação. Entenda o evento S-2220, os prazos e como manter tudo em dia.": "职业体检在eSocial中逾期会使企业面临处罚。了解S-2220事件、申报期限以及如何保持一切按时完成。",
 "Exames periódicos e demissionais": "定期体检与离职体检",
 "Exames periódicos vencidos, percebidos só quando o prazo já passou;": "定期体检过期，等到期限已过才被发现；",
 "Exames — Clínica Medicina Humana": "检查项目 — Medicina Humana诊所",
 "Exames, laudos e programas centralizados, com resultados rápidos e organizados.": "体检、鉴定报告和各项方案集中管理，结果快速且条理清晰。",
 "Existem diferentes estratégias, e a escolha depende do perfil de cada pessoa:": "策略多种多样，选择取决于每个人的具体情况：",
 "Expandir todas as categorias ⌄": "展开全部类别 ⌄",
 "Expandir todos os itens ⌄": "展开全部项目 ⌄",
 "Explore nosso espaço de forma imersiva: faça um tour virtual e descubra tudo!": "沉浸式探索我们的院区：来一次虚拟导览，尽览全貌！",
 "Falar pelo WhatsApp": "通过WhatsApp联系",
 "Fale com a Clínica Medicina Humana. Empresas: envie sua mensagem e a nossa equipe entra em contato.": "联系Clínica Medicina Humana。企业客户：请发送留言，我们的团队会与您联系。",
 "Fale com a gente e nós entramos em contato": "联系我们，我们会主动与您取得联系",
 "Fale com o RH": "联系人力资源部",
 "Fale com o Zezinho no WhatsApp ou ligue para a nossa central. Ajudamos você a marcar e tirar dúvidas sobre o preparo.": "通过WhatsApp联系Zezinho，或拨打我们的服务中心电话。我们会协助您预约，并解答检查前准备的疑问。",
 "Fale com o Zezinho pelo WhatsApp.": "通过WhatsApp联系Zezinho。",
 "Fale com o comercial": "联系商务团队",
 "Fale com o comercial. A gente vê quais Normas se aplicam à sua\n             atividade e monta a proposta sem compromisso.": "请联系商务团队。我们会评估哪些规范适用于贵公司的\n             业务，并提供免费报价方案。",
 "Falta de integração entre a clínica que faz o exame e o RH que envia o evento;": "开展体检的诊所与报送事件的人力资源部门之间缺乏衔接；",
 "Faça o Tour Virtual": "开始虚拟导览",
 "Faça parte da nossa equipe e cuide de pessoas com a gente.": "加入我们的团队，与我们一起关爱他人。",
 "Faça parte de um time que cuida de pessoas com atenção, ciência e carinho.": "加入一支以用心、科学和关爱照护他人的团队。",
 "Fechar": "关闭",
 "Fechar ✕": "关闭 ✕",
 "Fique por dentro": "了解最新动态",
 "Funcionários": "员工",
 "Função": "角色",
 "GRO": "GRO",
 "GRO e PGR: qual a diferença": "GRO与PGR：区别在哪里",
 "Gerenciamento de Riscos Ocupacionais (GRO)": "职业风险管理（GRO）",
 "Gerenciamento de riscos ocupacionais": "职业风险管理",
 "Gestor (tudo)": "管理员（全部权限）",
 "Ginecologista e Obstetra · 1958 a 2021": "妇产科医生 · 1958年至2021年",
 "Grandes ensaios clínicos deram base a esse entusiasmo. O programa de estudos com semaglutida para obesidade observou perdas de peso médias na faixa de 15% em pessoas que combinaram o tratamento com mudanças no estilo de vida. Em diabetes tipo 2, houve melhora consistente da hemoglobina glicada (HbA1c), marcador do controle da doença a médio prazo.": "大型临床试验为这种期待提供了依据。司美格鲁肽用于肥胖症的研究项目发现，将药物治疗与生活方式改变相结合的人群，平均减重幅度在15%左右。在2型糖尿病方面，反映中期病情控制水平的糖化血红蛋白（HbA1c）也持续改善。",
 "Historicamente, o rastreamento era recomendado a partir dos 50 anos. No entanto, estudos passaram a mostrar um aumento consistente de casos em adultos mais jovens ao longo das últimas décadas. Diante desse cenário, sociedades médicas revisaram suas recomendações e passaram a orientar o início aos 45 anos para quem não tem fatores de risco adicionais.": "以往，筛查通常建议从50岁开始。然而，多项研究显示，近几十年来年轻成年人的发病数持续上升。在这一背景下，各医学会修订了推荐意见，建议没有额外危险因素的人群从45岁开始筛查。",
 "Histórico familiar, excesso de peso, consumo elevado de sal, sedentarismo, estresse, tabagismo e idade aumentam o risco. Mas a hipertensão pode atingir qualquer pessoa, inclusive quem é jovem e se sente saudável.": "家族史、超重、高盐饮食、缺乏运动、压力、吸烟和年龄都会增加风险。但高血压可能发生在任何人身上，包括自我感觉健康的年轻人。",
 "Histórico organizado, que ampara a empresa em uma discussão trabalhista.": "健康档案完整有序，在劳动争议中为企业提供支撑。",
 "Hoje, cada paciente que passa pela Clínica Medicina Humana é acolhido com os valores que ele plantou. Seguimos honrando o seu nome, a sua história e a missão que ele nos deixou:": "如今，每一位来到Clínica Medicina Humana的患者，都会得到他所播下的价值观的接纳。我们继续以他的名字、他的故事和他留给我们的使命为荣：",
 "Home": "首页",
 "Homenagem ao Dr. José Carlos Prado Correia, eterno homenageado da Medicina Humana.": "谨此纪念Dr. José Carlos Prado Correia，Medicina Humana永远缅怀的人物。",
 "Horário de atendimento:": "服务时间：",
 "Hospital Promater": "Hospital Promater",
 "Hérnia de disco, lombalgia crônica e quadros de ansiedade não aparecem do dia para a noite. Eles dão sinais: queixas repetidas, alterações de exame, mudança no padrão de sono e de humor. O exame periódico é justamente o momento em que esses sinais podem ser identificados enquanto ainda cabem em um ajuste do posto de trabalho, e não em um afastamento de meses.": "椎间盘突出、慢性腰痛和焦虑症状不会在一夜之间出现。它们会发出信号：反复出现的不适主诉、检查指标的变化、睡眠和情绪模式的改变。定期体检正是发现这些信号的时机——此时通常只需对工作岗位做出调整，而不必面对长达数月的病假。",
 "Identificação precoce, que encurta ou evita o afastamento;": "及早发现，从而缩短甚至避免病休；",
 "Imprimir": "打印",
 "Imprimir / Salvar em PDF": "打印 / 保存为PDF",
 "Incentivar pausas e alongamentos ao longo do dia;": "鼓励在工作中适时休息和做拉伸；",
 "Insalubridade, periculosidade e laudos técnicos": "有害作业、危险作业与技术鉴定报告",
 "Instagram": "Instagram",
 "Insônia persistente, ronco alto com pausas na respiração (sinal de apneia do sono) e sonolência excessiva durante o dia merecem avaliação médica. Tratar esses problemas melhora não apenas as noites, mas a saúde como um todo.": "持续失眠、伴有呼吸暂停的响亮鼾声（睡眠呼吸暂停的信号）以及白天过度嗜睡，都值得就医评估。治疗这些问题改善的不只是夜晚，而是整体健康。",
 "Integrar as informações ao eSocial (eventos de SST);": "将相关信息整合报送至eSocial（SST事件）；",
 "Integração com o eSocial": "与eSocial对接",
 "Ir para os meus\n          treinamentos →": "前往我的\n          培训课程 →",
 "JC": "JC",
 "Junto dele caminham o S-2210, que comunica o acidente de trabalho, e o S-2240, que descreve as condições ambientais. Os três conversam entre si: uma informação fora de lugar em um deles contamina a leitura dos outros.": "与之配套的还有报告工伤事故的S-2210，以及描述作业环境条件的S-2240。这三者相互关联：其中任何一项信息填错，都会影响对其他两项的判读。",
 "Já fez o exame?": "已经做过体检了吗？",
 "Já o": "而",
 "Já tenho conta": "我已有账号",
 "Já tenho um código": "我已有代码",
 "LGPD": "LGPD",
 "LTCAT (Laudo Técnico das Condições Ambientais do Trabalho)": "LTCAT（工作环境条件技术鉴定报告）",
 "Laboratório": "检验科",
 "Lançar resultado": "录入结果",
 "Laudos e LTCAT": "技术报告与LTCAT",
 "Ler mais →": "阅读更多 →",
 "Liberados": "已发布",
 "Liberar meus cursos": "开通我的课程",
 "Ligue pra gente": "给我们打电话",
 "Login": "登录账号",
 "Mais de": "超过",
 "Mais de 45 especialidades médicas para todas as fases da vida.": "45个以上医学专科，覆盖人生各个阶段。",
 "Mais recentemente, pesquisas passaram a mostrar benefícios que vão além do peso e da glicose: em pessoas com sobrepeso ou obesidade e doença cardiovascular estabelecida, o tratamento foi associado à redução de eventos como infarto e AVC. Isso reforça a ideia de que a obesidade deve ser tratada como uma doença crônica, e não apenas uma questão estética.": "最近的研究还显示出超越体重和血糖之外的获益：在超重或肥胖且已确诊心血管疾病的人群中，该治疗与心肌梗死、脑卒中等事件的减少相关。这进一步印证了肥胖应被视为一种慢性疾病，而不仅仅是外形问题。",
 "Mantemos os seus dados apenas pelo tempo necessário para cumprir as finalidades descritas nesta política e as obrigações legais aplicáveis, especialmente aquelas relacionadas a registros de saúde.": "我们仅在实现本政策所述目的和履行适用法律义务（尤其是与健康记录相关的义务）所必需的期限内保存您的数据。",
 "Mantenha horários regulares para dormir e acordar, inclusive nos fins de semana;": "保持规律的就寝和起床时间，周末也不例外；",
 "Manter a empresa em conformidade com as Normas Regulamentadoras exige atenção constante: exames em dia, PGR atualizado, ASO e PCMSO corretos e os eventos de SST enviados ao eSocial no prazo. Um único detalhe fora do lugar pode se transformar em": "让企业持续符合监管条例（NR）的要求需要时刻留意：体检按期完成、PGR（风险管理计划）保持更新、ASO（职业健康证明）与PCMSO规范无误，并按期向eSocial报送SST（职业安全与健康）事件。任何一个细节出错，都可能演变为",
 "Manter o peso saudável e evitar o excesso de álcool;": "保持健康体重，避免过量饮酒；",
 "Mapa da Clínica Medicina Humana": "Medicina Humana诊所地图",
 "Mapear os riscos psicossociais dentro do PGR (Programa de Gerenciamento de Riscos);": "在PGR（风险管理计划）中梳理社会心理风险；",
 "Marque seus exames": "预约您的检查",
 "Marque seus exames pelo WhatsApp": "通过WhatsApp预约您的检查",
 "Medicina": "医疗",
 "Medicina Humana": "Medicina Humana",
 "Medicina Ocupacional": "职业健康服务",
 "Medicina Ocupacional para Empresas": "面向企业的职业健康服务",
 "Medicina Ocupacional para Empresas — Clínica Medicina Humana": "面向企业的职业医学服务 — Medicina Humana诊所",
 "Medicina Ocupacional · 1 de julho de 2026": "职业健康 · 2026年7月1日",
 "Medicina Ocupacional · 15 de julho de 2026": "职业健康 · 2026年7月15日",
 "Medicina Ocupacional · 16 de julho de 2026": "职业健康 · 2026年7月16日",
 "Medicina Ocupacional · 20 de julho de 2026": "职业医学 · 2026年7月20日",
 "Medicina Ocupacional · 6 de agosto de 2026": "职业医学 · 2026年8月6日",
 "Medicina Ocupacional · 7 de agosto de 2026": "职业健康 · 2026年8月7日",
 "Medicina Ocupacional — Clínica Medicina Humana": "职业医学 — Medicina Humana诊所",
 "Medicina ocupacional": "职业健康医学",
 "Medicina ocupacional para empresas: ASO, PCMSO, PGR/GRO, laudos, eSocial. Mantenha sua empresa em conformidade com as NRs.": "面向企业的职业医学服务：ASO、PCMSO、PGR/GRO、技术报告、eSocial。让贵公司符合各项NR要求。",
 "Medicina ocupacional: o que é e por que a sua empresa precisa": "职业医学：它是什么，以及贵公司为何需要它",
 "Medicina ocupacional: o que é e por que a sua empresa precisa desse serviço.": "职业医学：它是什么，以及贵公司为何需要这项服务。",
 "Medir a pressão regularmente, mesmo sem sintomas;": "即使没有症状，也要定期测量血压；",
 "Melhora a produtividade, o clima organizacional e a retenção de talentos;": "提升生产力、组织氛围和人才留存；",
 "Melhorar a experiência de navegação e os nossos serviços;": "改善浏览体验和我们的服务；",
 "Menos afastamentos e acidentes": "减少病假和事故",
 "Menos substituições, horas extras e retrabalho da equipe;": "减少人员替补、加班和团队返工；",
 "Meus módulos": "我的模块",
 "Meus treinamentos": "我的培训课程",
 "Mostramos só o miolo do número, o bastante para bater com o papel\n            na mão sem expor o documento de quem não pediu nada.": "我们只显示号码的中间部分，足以与您手中的\n            纸质文件核对，同时不会泄露他人的证件信息。",
 "Mudança de função / risco ocupacional": "岗位变更／职业风险变更",
 "Mudança de função sem o exame de mudança de risco correspondente.": "变更岗位却未做相应的风险变更体检。",
 "Multas e autuações do Ministério do Trabalho": "劳动部的罚款与行政处罚",
 "Médicos": "医生",
 "Médicos cadastrados": "已注册医师",
 "Mínimo 6 caracteres": "最少6个字符",
 "NR-1, GRO e PGR — Clínica Medicina Humana": "NR-1、GRO与PGR — Medicina Humana诊所",
 "NR-1, GRO e PGR: entenda o gerenciamento de riscos ocupacionais e as obrigações da empresa.": "NR-1、GRO与PGR：了解职业风险管理以及企业应尽的义务。",
 "NR-1, GRO e PGR: o que a sua empresa precisa saber": "NR-1、GRO与PGR：贵公司需要了解的要点",
 "NR35-0000-0000-0000": "NR35-0000-0000-0000",
 "Na Clínica Medicina Humana, acreditamos que cuidar bem das pessoas começa por cuidar bem de quem faz parte do nosso time. Buscamos profissionais comprometidos, empáticos e apaixonados por fazer a diferença na vida dos pacientes.": "在Clínica Medicina Humana，我们相信，善待他人首先要从善待团队成员开始。我们寻找的是尽职尽责、富有同理心、热衷于为患者生活带来改变的专业人才。",
 "Na prática, eles estimulam a liberação de insulina apenas quando a glicose está elevada, reduzem a produção de glucagon (hormônio que eleva o açúcar no sangue), retardam o esvaziamento do estômago e atuam em áreas do cérebro ligadas ao apetite, aumentando a sensação de saciedade. O resultado é melhor controle glicêmico e redução do consumo alimentar.": "在实际作用上，它们仅在血糖升高时才促进胰岛素释放，减少胰高血糖素（升高血糖的激素）的分泌，延缓胃排空，并作用于大脑中与食欲相关的区域，增强饱腹感。其结果是血糖控制更好，进食量减少。",
 "Natural de Aracaju (SE), o Dr. José Carlos formou-se em Medicina pela": "José Carlos医生出生于Aracaju（塞尔希培州），毕业于",
 "Nenhum medicamento é isento de riscos. Os efeitos colaterais mais comuns são gastrointestinais — náusea, vômito e alteração do funcionamento do intestino — geralmente mais intensos no início e que tendem a diminuir com o ajuste gradual da dose. Há situações em que o uso não é indicado, por isso a avaliação médica é indispensável.": "没有任何药物是完全没有风险的。最常见的副作用为胃肠道反应——恶心、呕吐和排便习惯改变——通常在用药初期较为明显，并会随着剂量的逐步调整而减轻。在某些情况下不宜使用，因此医生的评估必不可少。",
 "Nome": "姓名",
 "Nome completo": "姓名全称",
 "Nome completo*": "全名*",
 "Nome da empresa*": "公司名称*",
 "Nome do médico": "医生姓名",
 "Nome do paciente": "患者姓名",
 "Nome do responsável": "负责人姓名",
 "Nome*": "姓名*",
 "Nominal": "记名",
 "Nos últimos anos, uma classe de medicamentos conhecida como análogos do GLP-1 transformou a abordagem da obesidade e do diabetes tipo 2. Nomes como semaglutida, liraglutida e a mais recente tirzepatida passaram a ocupar o centro do debate — dentro e fora dos consultórios.": "近年来，一类被称为GLP-1类似物的药物改变了肥胖和2型糖尿病的治疗方式。司美格鲁肽、利拉鲁肽以及更新的替尔泊肽等药名，已成为诊室内外讨论的焦点。",
 "Nosso Homenageado": "我们纪念的人",
 "Nosso Homenageado · Medicina Humana": "我们纪念的人 · Medicina Humana",
 "Nosso Homenageado — Clínica Medicina Humana": "我们的纪念人物 — Medicina Humana诊所",
 "Nosso comercial atende empresas por telefone ou WhatsApp.": "我们的商务团队通过电话或WhatsApp为企业提供服务。",
 "Nosso compromisso é assegurar segurança e conforto em todas as fases do seu cuidado, com atendimento humano do começo ao fim.": "我们承诺在您就医的每一个环节都保障安全与舒适，从始至终提供有温度的服务。",
 "Nossos treinamentos": "我们的培训课程",
 "Notícias": "资讯",
 "Nova senha": "新密码",
 "Novo funcionário": "新增员工",
 "Novo médico": "新增医生",
 "Novo paciente": "新增患者",
 "Não encontrei esse treinamento. Fale com o comercial: a gente monta\n        turma para o que a sua operação precisa.": "未找到该培训。请联系商务团队：我们可以\n        根据贵公司运营的需要开班。",
 "Não fumar e cuidar do sono e do estresse;": "不吸烟，并管理好睡眠和压力；",
 "Não precisa de\n           cadastro nem de login": "无需注册\n           也无需登录",
 "Não vendemos os seus dados pessoais. O compartilhamento ocorre apenas quando necessário para a prestação do serviço (por exemplo, com laboratórios e profissionais de saúde envolvidos no seu cuidado), para cumprir exigências legais ou mediante o seu consentimento.": "我们不出售您的个人数据。仅在为提供服务所必需时（例如与参与您诊疗的检验机构和医务人员共享）、为遵守法律要求，或在取得您同意的情况下，才会共享数据。",
 "O ASO fica disponível para download no nosso sistema.": "ASO可在我们的系统中下载。",
 "O CPF sai protegido": "CPF以脱敏方式显示",
 "O GLP-1 (peptídeo semelhante ao glucagon tipo 1) é um hormônio produzido no intestino e liberado após as refeições. Ele participa da chamada resposta das incretinas, que ajuda o corpo a controlar a glicose. Os medicamentos análogos imitam a ação desse hormônio de várias formas ao mesmo tempo.": "GLP-1（胰高血糖素样肽-1）是一种由肠道分泌、在进餐后释放的激素。它参与所谓的肠促胰素反应，帮助身体控制血糖。这类类似物药物同时以多种方式模拟该激素的作用。",
 "O acesso é facilitado, com sinalização clara para que você chegue com tranquilidade ao seu atendimento. Se preferir, use o mapa abaixo para traçar a melhor rota até a clínica.": "前往诊所十分便利，沿途标识清晰，让您从容抵达就诊。您也可以使用下方地图规划到诊所的最佳路线。",
 "O atendimento assistencial está de volta, com a nossa equipe à disposição e o acolhimento de sempre.": "门诊医疗服务已恢复，我们的团队随时为您服务，一如既往地用心接待。",
 "O caminho mais simples é concentrar a medicina ocupacional em um só lugar: quem realiza o exame já entrega a informação no formato que o eSocial espera, com o controle de vencimentos feito antes de a data passar — e não depois.": "最简单的办法是把职业医学集中在一个地方：实施体检的机构直接按照eSocial要求的格式提交信息，并在到期日之前——而不是之后——完成有效期管控。",
 "O câncer colorretal é um dos tumores mais frequentes no mundo — e também um dos mais evitáveis quando detectado cedo. Nos últimos anos, diretrizes internacionais anteciparam a idade de início do rastreamento de 50 para 45 anos em pessoas com risco médio. Entenda o porquê.": "结直肠癌是全球最常见的肿瘤之一——同时也是早期发现后最可预防的肿瘤之一。近年来，国际指南已将中等风险人群的筛查起始年龄从50岁提前到45岁。了解其中的原因。",
 "O código fica no rodapé do certificado, junto da data\n           de emissão.": "该代码位于证书底部，与签发日期在一起。",
 "O documento traz as horas do treinamento e até quando ele vale.\n            É por essa data que se sabe quando reciclar.": "证书上载明培训学时以及有效期至何时。\n            正是根据这个日期来确定何时进行复训。",
 "O evento": "报送事件",
 "O lema que traduz, até hoje, o legado do nosso homenageado.": "这句箴言至今仍诠释着我们所纪念之人留下的精神。",
 "O nome e o CPF saem no certificado. Confira antes de continuar.": "姓名和CPF会显示在证书上。请核对无误后再继续。",
 "O nosso compromisso maior é com a sua saúde. Por isso, investimos continuamente em uma": "我们最大的承诺是守护您的健康。因此，我们持续投入建设一支",
 "O pedido não é uma confirmação automática: a data só está garantida depois do nosso retorno.": "该申请并不等于自动确认：日期需在我们回复后才最终确定。",
 "O que a empresa ganha com o periódico em dia": "定期体检按时完成，企业能收获什么",
 "O que a empresa precisa enviar": "企业需要报送什么",
 "O que acontece enquanto dormimos": "睡眠时身体发生了什么",
 "O que ajuda a prevenir": "哪些做法有助于预防",
 "O que diz a norma": "条例是怎么规定的",
 "O que dizem os estudos": "研究结论怎么说",
 "O que os números mostram": "数据说明了什么",
 "O que são e como agem": "它们是什么，如何起作用",
 "O que são riscos psicossociais": "什么是社会心理风险",
 "O que é a NR-1": "什么是NR-1",
 "O que é medicina ocupacional": "什么是职业健康医学",
 "O que é o ASO": "什么是ASO",
 "O que é o PCMSO": "什么是PCMSO",
 "O rastreamento é importante justamente porque a doença pode ser silenciosa no início. Ainda assim, alguns sintomas merecem avaliação médica: sangue nas fezes, mudança persistente no hábito intestinal, dor abdominal que não passa, perda de peso sem causa aparente e anemia.": "筛查之所以重要，正是因为这种疾病在早期可能没有任何症状。即便如此，有些症状仍需就医评估：便血、排便习惯持续改变、腹痛不缓解、不明原因的体重下降以及贫血。",
 "O resultado fica": "检查结果处于",
 "O sono não é um período de \"desligamento\" do corpo. Durante a noite, o organismo consolida memórias, regula hormônios, repara tecidos e reorganiza funções essenciais. É também nesse momento que o sistema imunológico produz substâncias que ajudam a defender o corpo contra infecções.": "睡眠并不是身体“关机”的一段时间。夜间，身体会巩固记忆、调节激素、修复组织并重新调整各项基本功能。免疫系统也正是在这个时候产生帮助抵御感染的物质。",
 "O trabalhador usa o código, cria a conta com o CPF e assiste no seu tempo.": "劳动者使用该代码，用CPF注册账号，按自己的时间观看课程。",
 "O uso deve ser individualizado e acompanhado por um profissional de saúde;": "用药必须个体化，并在医务人员的指导下进行；",
 "Observações (opcional): horário de preferência, nomes dos funcionários, exames complementares...": "备注（选填）：偏好时段、员工姓名、补充检查项目……",
 "Oferecer acompanhamento e encaminhamento quando necessário.": "必要时提供随访和转诊。",
 "Onde as empresas mais tropeçam": "企业最容易出错的地方",
 "Oportunidades de desenvolvimento, capacitação e evolução na carreira.": "提供发展、培训和职业晋升的机会。",
 "Organizar o ritmo e evitar a sobrecarga de repetição;": "合理安排节奏，避免重复性动作造成的超负荷；",
 "Orçamento": "报价",
 "Os": "各项",
 "Os principais eventos de SST que acompanhamos para a sua empresa são:": "我们为贵公司跟进的主要SST（职业安全与健康）事件包括：",
 "Os riscos de ignorar": "忽视的代价",
 "Os riscos de não estar em conformidade": "不合规将面临的风险",
 "Ou fale com o comercial por e-mail:": "或通过电子邮件联系商务部：",
 "Ou, se preferir, escolha abaixo a letra inicial da especialidade que você procura.": "或者，您也可以在下方选择所查找专科的首字母。",
 "Outra": "其他",
 "Outro (descrever nas observações)": "其他（请在备注中说明）",
 "Ouvidoria": "意见受理中心",
 "Ouvidoria da Clínica Medicina Humana — registre reclamações, sugestões e elogios.": "Clínica Medicina Humana意见受理中心 — 提交投诉、建议和表扬。",
 "Ouvidoria — Clínica Medicina Humana": "意见与投诉 — Medicina Humana诊所",
 "PCMSO (Programa de Controle Médico de Saúde Ocupacional)": "PCMSO（职业健康医学监护计划）",
 "PCMSO alimentado com dados reais, e não com formulário repetido;": "PCMSO以真实数据为基础，而不是重复套用表格；",
 "PGR (Programa de Gerenciamento de Riscos)": "PGR（风险管理计划）",
 "PGR / GRO (NR-1)": "PGR / GRO（NR-1）",
 "PPP (Perfil Profissiográfico Previdenciário)": "PPP（社保职业履历档案）",
 "Paciente": "患者",
 "Pacientes": "患者",
 "Pacientes cadastrados": "已登记患者",
 "Painel da Equipe": "团队管理面板",
 "Painel da Equipe — Clínica Medicina Humana": "团队工作台 — Medicina Humana诊所",
 "Painel da equipe · Resultados de exames": "团队管理面板 · 检查结果",
 "Para a maioria dos adultos, a recomendação fica entre 7 e 9 horas por noite. Mais importante do que apenas a quantidade é a qualidade e a regularidade do sono. Algumas medidas simples ajudam:": "对大多数成年人而言，建议每晚睡7至9小时。比睡眠时长更重要的是睡眠质量和规律性。一些简单的做法会有帮助：",
 "Para entregar tudo isso, contamos com um": "为实现这一切，我们拥有",
 "Para exercer os seus direitos ou esclarecer dúvidas sobre esta política, entre em contato com a Clínica Medicina Humana pelo telefone (71) 3493-7220 ou pelo endereço R. do Alecrim, 76, Centro, Camaçari - BA.": "如需行使您的权利或就本政策提出疑问，请拨打电话 (71) 3493-7220 或前往 R. do Alecrim, 76, Centro, Camaçari - BA 联系Medicina Humana诊所。",
 "Para informações ou para exercer os seus direitos previstos na LGPD.": "如需了解信息或行使LGPD赋予您的权利。",
 "Passivos trabalhistas e ações judiciais de ex-colaboradores": "劳动纠纷负债与前员工提起的诉讼",
 "Passou na prova, baixa o certificado, nominal, com carga horária e validade.": "通过考试后即可下载证书，证书记名，载明学时和有效期。",
 "Pedir proposta no WhatsApp": "通过WhatsApp索取报价",
 "Pegue seu ASO": "领取您的ASO",
 "Pendentes": "待处理",
 "Pendências e inconsistências no eSocial (SST)": "eSocial（SST）中的待处理事项与数据不一致",
 "Periódico": "定期体检",
 "Periódico:": "定期体检：",
 "Periódicos e demissionais": "定期体检与离职体检",
 "Peça uma proposta sem compromisso. Conte quantos colaboradores tem a sua empresa e nós montamos o pacote ideal — com conformidade garantida.": "索取报价，无需任何承诺。告诉我们贵公司有多少名员工，我们为您量身定制最合适的方案——并保证合规。",
 "Pioneiros no segmento, temos orgulho de uma história de superação e liderança. Atuamos em diversas localidades do estado, com": "作为行业先驱，我们为一路克服困难、引领发展的历程感到自豪。我们的服务遍及巴伊亚州多个地区，拥有",
 "Podemos coletar dados que você fornece diretamente — como nome, telefone, e-mail, data de nascimento e informações necessárias para agendamentos e atendimentos — e dados coletados automaticamente durante a navegação no site, como endereço IP, tipo de dispositivo e páginas visitadas, por meio de cookies e tecnologias semelhantes.": "我们可能收集您直接提供的数据——例如姓名、电话、电子邮箱、出生日期以及预约和就诊所需的信息——以及您浏览本网站时通过cookie和类似技术自动收集的数据，例如IP地址、设备类型和访问过的页面。",
 "Política de Privacidade": "隐私政策",
 "Política de Privacidade da Clínica Medicina Humana — proteção de dados e LGPD.": "Medicina Humana诊所隐私政策——数据保护与LGPD。",
 "Política de Privacidade — Clínica Medicina Humana": "隐私政策 — Medicina Humana诊所",
 "Por que a idade mudou": "起始年龄为何调整",
 "Por que a sua empresa precisa": "贵公司为什么需要它",
 "Por que fazer parte": "为什么加入我们",
 "Por que isso importa para a empresa": "这对企业为何重要",
 "Por que isso passa primeiro pela clínica": "为什么这件事首先要从诊所做起",
 "Por que manter tudo em dia": "为什么要保持一切按时完成",
 "Por que ter a Clínica Medicina Humana como parceira": "为什么选择Clínica Medicina Humana作为合作伙伴",
 "Por que é perigosa": "为什么它很危险",
 "Praticar atividade física com regularidade;": "坚持规律的体育锻炼；",
 "Precisa de ajuda?": "需要帮助吗？",
 "Precisa de ajuda? Entre em contato através dos canais abaixo.": "需要帮助吗？请通过以下渠道联系我们。",
 "Preencha o formulário ao lado com os dados da sua empresa e a sua mensagem. Nossa equipe comercial retorna o contato o mais breve possível.": "请在旁边的表单中填写贵公司的资料和您的留言。我们的商务团队会尽快与您联系。",
 "Preencha o formulário ao lado. Nossa equipe confere a agenda e confirma o dia e o horário com você por e-mail ou telefone.": "请填写旁边的表单。我们的团队会核对排期，并通过电子邮件或电话与您确认具体日期和时间。",
 "Preencha os dados abaixo. Ao enviar, sua candidatura é encaminhada pelo WhatsApp (você poderá anexar o currículo em PDF na conversa).": "请填写以下信息。提交后，您的应聘申请将通过WhatsApp转达（您可以在对话中附上PDF格式的简历）。",
 "Prefere agendar falando?": "更想通过通话预约吗？",
 "Prefere e-mail? Escreva para a nossa equipe.": "更习惯用电子邮件？请写信给我们的团队。",
 "Prefere por e-mail?": "更愿意通过电子邮件？",
 "Pressão alta: o inimigo silencioso que pede atenção o ano todo": "高血压：需要全年关注的沉默杀手",
 "Pressão alta: o inimigo silencioso que pede atenção o ano todo — Clinica Medicina Humana": "高血压：需要全年关注的沉默杀手 — Clinica Medicina Humana",
 "Prevenir sai mais barato": "预防的成本更低",
 "Prevenção e acompanhamento que diminuem custos e aumentam a produtividade.": "预防与跟踪管理，降低成本、提升生产力。",
 "Prevenção · 26 de junho de 2026": "预防 · 2026年6月26日",
 "Primeira vez? Use a aba": "首次使用？请使用",
 "Privacidade": "隐私政策",
 "Procurando o melhor acesso…": "正在为您寻找最佳入口…",
 "Procurar treinamento": "搜索培训课程",
 "Procurar treinamento (ex.: altura, NR-10, empilhadeira)": "搜索培训（例如：高处作业、NR-10、叉车）",
 "Pronto para agendar o seu exame?": "准备好预约您的检查了吗？",
 "Proposta sem compromisso · conformidade garantida": "免费报价 · 保证合规",
 "Protege a empresa de multas, autuações e passivos trabalhistas;": "使企业免于罚款、行政处罚和劳动纠纷负债；",
 "Proteção contra multas e passivos": "避免罚款和法律责任",
 "Próximo slide": "下一张",
 "Quais serviços fazem parte": "包含哪些服务",
 "Quando procurar ajuda": "何时该寻求帮助",
 "Quantidade de pessoas*": "人数*",
 "Quanto dormir e como melhorar": "该睡多久以及如何改善睡眠",
 "Quem Somos": "关于我们",
 "Quem Somos — Clínica Medicina Humana": "关于我们 — Clínica Medicina Humana",
 "Quem Somos — Clínica Medicina Humana: cuidado completo, tecnologia avançada e atendimento humano.": "关于我们 — Medicina Humana诊所：全方位照护、先进技术和有温度的服务。",
 "Quem deve se preocupar": "哪些人需要特别注意",
 "Quem possui histórico familiar, doenças inflamatórias intestinais ou síndromes genéticas pode precisar começar ainda antes e com intervalos diferentes — por isso a avaliação individual é fundamental.": "有家族史、炎症性肠病或遗传综合征的人可能需要更早开始筛查，并采用不同的筛查间隔——因此个体化评估至关重要。",
 "Quem recebe o certificado (auditor, contratante, cliente) confere\n            aqui mesmo, sem precisar de conta.": "收到证书的一方（审计人员、发包方、客户）无需注册账号，在此即可查验。",
 "Quer o treinamento certo para a sua equipe?": "想为您的团队找到合适的培训吗？",
 "R$ 336 mil por infração": "每项违规33.6万雷亚尔",
 "R. do Alecrim, 76": "R. do Alecrim, 76",
 "R. do Alecrim, 76, Centro, Camaçari - BA, 42800-025": "R. do Alecrim, 76, Centro, Camaçari - BA, 42800-025",
 "R. do Alecrim, 76, Centro, Camaçari/BA": "R. do Alecrim, 76, Centro, Camaçari/BA",
 "Rastreamento do câncer colorretal aos 45 anos — Clínica Medicina Humana": "45岁起进行结直肠癌筛查 — Medicina Humana诊所",
 "Rastreamento do câncer colorretal: por que a idade de início passou para 45 anos.": "结直肠癌筛查：起始年龄为何调整为45岁。",
 "Realizados": "开展时间为",
 "Realizar a Análise Ergonômica do Trabalho periodicamente.": "定期开展工作工效学分析。",
 "Realizar agendamentos, atendimentos e a comunicação com você;": "安排预约、提供诊疗服务并与您沟通；",
 "Realizar os exames e o acompanhamento médico previstos nas NRs;": "开展各项NR规定的体检和医学随访；",
 "Recebe um código": "收到一个代码",
 "Recebeu um certificado da nossa equipe e quer ter\n           certeza de que é verdadeiro? Digite o código impresso no documento.\n           A conferência é direta na nossa base.": "收到了我们团队颁发的证书，想\n           确认其真伪？请输入印在文件上的编码，\n           系统将直接在我们的数据库中核验。",
 "Recepção (lança)": "前台（录入）",
 "Recepção / Atendimento": "前台 / 接待",
 "Recepção e atendimento": "前台与接待",
 "Reclamação": "投诉",
 "Reconhecimento": "认可与肯定",
 "Reduz afastamentos, acidentes e doenças ocupacionais;": "减少病休、事故和职业病；",
 "Reduza a exposição a telas e luz intensa nas horas que antecedem o sono;": "睡前数小时减少接触屏幕和强光；",
 "Reduzir o sal e os alimentos ultraprocessados;": "减少食盐和超加工食品的摄入；",
 "Região de atendimento*": "服务地区*",
 "Repita a senha": "再次输入密码",
 "Responsável Técnico (libera)": "技术负责人（放行）",
 "Resultados de Exames": "检查结果",
 "Resultados de Exames — Clínica Medicina Humana": "检查结果 — Clínica Medicina Humana",
 "Resultados pendentes de liberação": "待发布的检查结果",
 "Retorno ao trabalho": "复工体检",
 "Rever a organização do trabalho, as metas e as jornadas;": "重新审视工作组织方式、绩效目标和工时安排；",
 "Riscos psicossociais em foco": "聚焦社会心理风险",
 "S-2210 — Comunicação de Acidente de Trabalho (CAT):": "S-2210 — 工伤事故报告（CAT）：",
 "S-2220 — Monitoramento da Saúde do Trabalhador": "S-2220 — 劳动者健康监护",
 "S-2220 — Monitoramento da Saúde do Trabalhador:": "S-2220 — 劳动者健康监护：",
 "S-2240 — Condições Ambientais do Trabalho:": "S-2240 — 作业环境条件：",
 "Saiba mais": "了解更多",
 "Sair": "退出",
 "Sala de aula": "课堂",
 "Salvador": "Salvador",
 "Salvar nova senha": "保存新密码",
 "Saúde e segurança do trabalho com conformidade, agilidade e tranquilidade para a sua empresa.": "为贵公司提供合规、高效、省心的职业安全与健康服务。",
 "Saúde mental no trabalho: o que muda com os riscos psicossociais na NR-1": "职场心理健康：NR-1中的社会心理风险带来哪些变化",
 "Saúde mental no trabalho: o que muda com os riscos psicossociais na NR-1 — Clinica Medicina Humana": "职场心理健康：NR-1纳入社会心理风险带来哪些变化 — Clinica Medicina Humana",
 "Saúde · 10 de julho de 2026": "健康 · 2026年7月10日",
 "Saúde · 18 de julho de 2026": "健康 · 2026年7月18日",
 "Saúde, prevenção, bem-estar e medicina ocupacional. Fique por dentro.": "健康、预防、养生与职业医学。及时了解最新资讯。",
 "Se a página não abrir sozinha, escolha uma opção:": "如果页面没有自动打开，请选择一个选项：",
 "Se o código não funcionar ou as vagas tiverem acabado, fale com o\n             RH da sua empresa.": "如果代码无法使用或名额已满，请联系\n             贵公司的人力资源部。",
 "Seg. a sex., 7h às 18h · Sáb., 7h às 12h": "周一至周五 7:00-18:00 · 周六 7:00-12:00",
 "Seguir o tratamento e nunca interromper a medicação por conta própria.": "坚持治疗，切勿自行停药。",
 "Segundo dados do INSS, as": "根据INSS的数据，",
 "Segurança do Trabalho": "劳动安全",
 "Segurança do Trabalho · 8 de julho de 2026": "劳动安全 · 2026年7月8日",
 "Segurança e Saúde no Trabalho (SST)": "职业安全与健康（SST）",
 "Semaglutida e o tratamento da obesidade — Clínica Medicina Humana": "司美格鲁肽与肥胖症的治疗 — Clínica Medicina Humana",
 "Semaglutida e os análogos de GLP-1 no tratamento da obesidade e do diabetes tipo 2.": "司美格鲁肽及GLP-1类似物在肥胖症和2型糖尿病治疗中的应用。",
 "Semaglutida: o novo capítulo no tratamento da obesidade e do diabetes tipo 2": "司美格鲁肽：肥胖和2型糖尿病治疗的新篇章",
 "Senha": "密码",
 "Serviços": "服务项目",
 "Serviços que a sua empresa encontra aqui": "贵公司在这里可获得的服务",
 "Seus resultados": "您的检查结果",
 "Sinais de alerta": "警示信号",
 "Site da clínica": "诊所官网",
 "Site principal": "主站",
 "Slide anterior": "上一张",
 "Solicitar agendamento": "提交预约申请",
 "Solicitar orçamento": "索取报价",
 "Solicite o agendamento dos exames da sua empresa": "为贵公司申请体检预约",
 "Somente a saúde mental respondeu por mais de": "仅心理健康问题一项就造成了超过",
 "Sono e imunidade": "睡眠与免疫力",
 "Sono e imunidade — Clínica Medicina Humana": "睡眠与免疫力 — Clínica Medicina Humana",
 "Sono e imunidade: por que dormir bem protege a sua saúde": "睡眠与免疫力：为什么睡好觉能保护您的健康",
 "Sono e imunidade: por que dormir bem protege a sua saúde.": "睡眠与免疫力：为什么睡好觉能保护您的健康。",
 "Sou Médico": "我是医生",
 "Sou Paciente": "我是患者",
 "Status": "状态",
 "Sua empresa compra uma vez e recebe um código só. Nada de cadastrar\n           gente uma a uma.": "贵公司一次采购，只需领取一个代码。不必逐个为员工注册。",
 "Sua empresa em conformidade: cuidamos dos eventos de saúde e segurança do trabalho e do envio ao eSocial no prazo, sem multas.": "让贵公司保持合规：我们负责职业安全与健康事件的处理，并按时上报eSocial，杜绝罚款。",
 "Sua empresa precisa de medicina ocupacional? Envie uma mensagem e a nossa equipe entra em contato com você.": "贵公司需要职业健康服务吗？请给我们留言，我们的团队会与您联系。",
 "Sua empresa sempre em dia com a CLT, as NRs e o eSocial — sem sustos em fiscalizações.": "让贵公司始终符合CLT（巴西劳动法）、各项NR和eSocial的要求——监督检查不再措手不及。",
 "Sua senha": "您的密码",
 "Sugestão": "建议",
 "São fatores ligados à forma como o trabalho é organizado e às relações no ambiente profissional que podem afetar a saúde mental e física do trabalhador. Entram nessa lista a sobrecarga de tarefas, prazos excessivos, assédio moral, falta de autonomia, jornadas exaustivas e conflitos frequentes.": "这些因素与工作的组织方式以及职场人际关系有关，可能影响劳动者的身心健康。其中包括任务超负荷、工期过紧、职场精神霸凌、缺乏自主权、超长工时以及频繁的冲突。",
 "Também elaboramos": "我们还负责编制",
 "Telefone": "电话",
 "Telefone*": "电话*",
 "Telefone:": "电话：",
 "Tenho um código": "我有代码",
 "Teste imunoquímico fecal (FIT):": "粪便免疫化学检测（FIT）：",
 "Tipo do exame*": "体检类型*",
 "Tire dúvidas sobre vagas e processos.": "咨询职位空缺与招聘流程的相关问题。",
 "Toda grande história começa com um sonho, e o da Medicina Humana tem um nome:": "每一段伟大的故事都始于一个梦想，而Medicina Humana的这个梦想有一个名字：",
 "Todo o período": "全部时间",
 "Todos os cursos": "全部课程",
 "Tour Virtual": "虚拟导览",
 "Trabalhador: acesse e baixe o seu Atestado de Saúde Ocupacional online.": "劳动者：在线查看并下载您的职业健康证明（ASO）。",
 "Trabalhe Conosco": "加入我们",
 "Trabalhe Conosco — Clínica Medicina Humana": "加入我们 — Medicina Humana诊所",
 "Trabalhe com tecnologia de ponta e ambientes preparados para você.": "使用先进的技术设备，在为您精心准备的环境中工作。",
 "Trabalhe conosco na Clínica Medicina Humana — envie seu currículo e faça parte do nosso time.": "加入Medicina Humana诊所——投递简历，成为我们团队的一员。",
 "Treinamento NRs": "NR培训",
 "Treinamento em NRs": "NR培训",
 "Treinamentos": "培训课程",
 "Treinamentos em NRs": "NR培训",
 "Treinamentos em NRs | Clínica Medicina Humana": "NR培训 | Medicina Humana诊所",
 "Treinamentos em Normas Regulamentadoras para empresas.": "面向企业的监管条例（NR）培训。",
 "Treinamentos em Normas Regulamentadoras para empresas: NR-10, NR-33, NR-35 e mais, com instrutores qualificados, prova e certificado.": "面向企业的监管条例（NR）培训：NR-10、NR-33、NR-35等，由具备资质的讲师授课，含考试与证书。",
 "Trocar senha": "修改密码",
 "Técnico(a) de enfermagem": "护理技术员",
 "Técnicos de enfermagem": "护理技术员",
 "Um afastamento prolongado custa à empresa muito mais do que o programa de saúde ocupacional do ano inteiro — sem contar o custo humano para o trabalhador e a família.": "一次长期病假给企业带来的成本，远高于全年的职业健康计划费用——这还不包括劳动者及其家庭承受的人力代价。",
 "Um código só, para repassar a toda a equipe por e-mail ou no grupo.": "只需一个代码，即可通过邮件或群组发给整个团队。",
 "Um lugar onde respeito, empatia e trabalho em equipe são levados a sério.": "在这里，尊重、同理心和团队协作被真正当回事。",
 "Um novo conceito em cuidar de você, com tecnologia de ponta, estrutura diferenciada e equipe médica e assistencial altamente qualificada.": "以尖端技术、优质设施以及高素质的医疗和护理团队，为您带来全新的健康照护理念。",
 "Uma atualização importante incluiu os": "一项重要的修订将",
 "Uma consulta e uma medição simples podem revelar o que o corpo não avisa. O acompanhamento regular é o melhor caminho para manter a pressão sob controle.": "一次问诊和一次简单的测量，就能发现身体没有发出信号的问题。定期随访是把血压控制好的最佳途径。",
 "Uma das atualizações mais relevantes é a inclusão dos": "其中最重要的更新之一，是纳入了",
 "Uma homenagem a quem plantou a semente do nosso cuidado.": "谨此致敬那位播下我们关爱种子的人。",
 "Universidade Federal de Sergipe": "塞尔希培联邦大学",
 "Usar o código da empresa": "使用企业代码",
 "Use o mesmo código que a sua\n              empresa enviou. Se não tiver mais o código em mãos, peça ao RH.": "请使用贵公司发送的\n              同一个代码。如果您手头已没有该代码，请向人力资源部索取。",
 "Usuário": "用户名",
 "Utilizamos as suas informações para as seguintes finalidades:": "我们将您的信息用于以下目的：",
 "Utilizamos cookies para o funcionamento do site, análise de navegação e melhoria da sua experiência. Você pode gerenciar ou desativar os cookies nas configurações do seu navegador, ciente de que algumas funcionalidades podem ser afetadas.": "我们使用cookie来保障网站运行、分析访问情况并改善您的使用体验。您可以在浏览器设置中管理或停用cookie，但请注意部分功能可能因此受到影响。",
 "Utilize o campo abaixo para encontrar os cuidados certos para você.": "请使用下方的搜索框，找到适合您的诊疗服务。",
 "Validar": "验证",
 "Validar certificado": "验证证书",
 "Validar certificado | Clínica Medicina Humana": "证书验证 | Clínica Medicina Humana",
 "Validação de certificado": "证书验证",
 "Valorizamos o esforço e o cuidado de cada pessoa do time.": "我们重视团队中每个人的付出与用心。",
 "Ver mais novidades →": "查看更多资讯 →",
 "Ver no mapa": "在地图中查看",
 "Ver os cursos": "查看课程",
 "Ver os treinamentos em NRs": "查看NR培训课程",
 "Ver política de privacidade.": "查看隐私政策。",
 "Ver serviços de medicina ocupacional →": "查看职业健康服务 →",
 "Ver todas →": "查看全部 →",
 "Ver todos": "查看全部",
 "Ver treinamentos": "查看培训课程",
 "Vincula ao médico": "关联至医师",
 "Visualizador de exame": "检查报告查看器",
 "Visão geral": "总览",
 "Você diz quais Normas e quantas pessoas. O comercial fecha e libera.": "您来定需要哪些规范、多少人参加。商务团队完成签约并开通。",
 "Você já está conectado.": "您已经登录。",
 "Voltar": "返回",
 "WhatsApp": "WhatsApp",
 "WhatsApp (com DDD)": "WhatsApp（含区号）",
 "WhatsApp:": "WhatsApp：",
 "Zezinho": "Zezinho",
 "a senha que você criou": "您设置的密码",
 "acompanham a saúde do trabalhador ao longo do contrato, em intervalos definidos conforme o risco da função, a idade e as normas aplicáveis, detectando precocemente qualquer alteração relacionada ao trabalho.": "在整个劳动合同期内跟踪劳动者的健康状况，按照岗位风险、年龄和适用条例确定的间隔期进行，以便及早发现任何与工作相关的异常。",
 "agendar os exames pelo site": "通过网站预约体检",
 "antes de o colaborador iniciar as atividades": "在员工开始工作之前",
 "antes do início das atividades;": "在开始工作之前；",
 "ao da realização do exame.": "，自体检当月起算。",
 "aposentadoria especial": "特殊工种退休",
 "após afastamentos;": "在病休之后进行；",
 "até ser liberado pelo responsável. Só depois o paciente vê.": "状态，直到负责人放行。之后患者才能看到。",
 "carrega mais de": "拥有超过",
 "centenas de clientes satisfeitos": "数百家满意的客户",
 "certificado por pessoa": "每人一张证书",
 "clinicamedicinahumana2@gmail.com": "clinicamedicinahumana2@gmail.com",
 "com o\n              cupom que a sua empresa enviou.": "选项卡，输入贵公司发送给您的兑换码。",
 "com o Assistencial": "临床门诊服务重新开放",
 "comercial@medicinahumana.com.br": "comercial@medicinahumana.com.br",
 "como deve sair no certificado": "证书上应显示的姓名",
 "considerada o exame padrão. Permite visualizar todo o intestino grosso e, no mesmo procedimento, remover pólipos que poderiam evoluir para câncer;": "被视为标准检查。它可以观察整个大肠，并在同一次操作中切除可能发展为癌症的息肉；",
 "consultas, exames e programas personalizados": "门诊、检查和定制化健康方案",
 "corretamente e no prazo": "正确并按时交付",
 "cuidar de gente com humanidade": "以人为本地关爱他人",
 "de saúde ocupacional e gestão de riscos, para organizações de todos os setores e portes. O resultado são ambientes mais saudáveis, seguros e produtivos, com pessoas mais bem cuidadas.": "，涵盖职业健康与风险管理，面向各行业、各种规模的组织。由此带来的是更健康、更安全、更高效的工作环境，以及得到更好照护的员工。",
 "dia 15 do mês seguinte": "次月15日",
 "digite o código do certificado": "请输入证书代码",
 "documenta a exposição do trabalhador a agentes nocivos e é fundamental para a": "记录劳动者接触有害因素的情况，是办理",
 "doenças da coluna": "脊柱疾病",
 "duas décadas de experiência e tradição": "二十多年的经验与传承",
 "e apoiamos a emissão do": "并协助出具",
 "e o respeito de pacientes, empresas e parceiros, sempre com a mesma vocação: cuidar de você em cada detalhe.": "，以及患者、企业和合作伙伴的尊重，始终秉持同样的使命：细致入微地呵护您。",
 "e os": "以及",
 "e uma busca constante por tecnologia e inovação.": "，并持续追求技术与创新。",
 "eSocial": "eSocial",
 "eSocial (SST)": "eSocial（SST）",
 "eSocial — saiba mais": "eSocial — 了解更多",
 "eSocial: exame ocupacional fora do prazo saiu caro para as empresas": "eSocial：职业健康体检逾期，企业代价高昂",
 "eSocial: exame ocupacional fora do prazo saiu caro para as empresas — Clínica Medicina Humana": "eSocial：职业体检逾期让企业付出高昂代价 — Medicina Humana诊所",
 "em 2025, recorde histórico. Entre as mulheres, a dor na coluna aparece à frente, seguida dos transtornos de ansiedade; entre os homens, as fraturas de perna e tornozelo lideram, com dores nas costas e hérnia de disco logo atrás.": "2025年创历史新高。在女性中，脊柱疼痛位居首位，其次是焦虑障碍；在男性中，腿部和踝部骨折居首，紧随其后的是背痛和椎间盘突出。",
 "em intervalos definidos conforme o risco e a idade;": "按照风险和年龄确定的间隔期进行；",
 "envio dos dados de cada ASO (admissional, periódico, de retorno ao trabalho, de mudança de função e demissional).": "上报每一份ASO的数据（入职、定期、复工、岗位变更和离职体检）。",
 "equipe inteira": "整个团队",
 "equipe técnica de profissionais especializados e comprometidos": "专业过硬、尽职尽责的技术团队",
 "espaço amplo, infraestrutura moderna": "宽敞的空间和现代化的设施",
 "ex.: admin": "例如：admin",
 "ex.: maria": "例：maria",
 "exame demissional": "离职体检",
 "exames periódicos": "定期体检",
 "gera e organiza esses eventos a partir dos exames e laudos": "依据所开展的体检和出具的报告生成并整理这些事件",
 "ginecologista e obstetra": "妇产科医生",
 "junto ao INSS.": "（向INSS申请）的重要依据。",
 "laudos de insalubridade e periculosidade": "有害作业与危险作业鉴定报告",
 "leva ao eSocial o resultado de cada Atestado de Saúde Ocupacional (ASO): admissional, periódico, de retorno ao trabalho, de mudança de risco e demissional. O prazo de envio vai até o": "将每一份职业健康证明（ASO）的结果上报eSocial：入职、定期、复工、风险变更和离职体检。提交期限截至",
 "lideraram as concessões do benefício por incapacidade temporária. Dores nas costas e lesões de disco, como a hérnia, seguem no topo do ranking nacional de licenças médicas.": "在暂时丧失劳动能力津贴的批准数量中位居前列。背痛和椎间盘病变（如椎间盘突出）仍高居全国病假原因排行榜首位。",
 "multa, autuação ou processo trabalhista": "罚款、行政处罚或劳动诉讼",
 "multas, pendências e problemas em fiscalizações": "罚款、待办事项以及监督检查中的问题",
 "na Bahia.": "领域，在巴伊亚州。",
 "no encerramento do contrato.": "在合同终止时进行。",
 "no mercado de saúde. Com um olhar cuidadoso e responsável, tornou-se um dos nomes mais respeitados em": "的医疗行业经验与传承。凭借细致而负责的态度，我们已成为最受尊敬的品牌之一，涵盖",
 "nos casos mais graves. Mais relevante que o valor, porém, é a forma de detecção: o eSocial confronta o que a empresa declara com as bases do INSS, da Receita Federal e do Ministério do Trabalho, e aponta as inconsistências na hora.": "，适用于最严重的情形。不过，比金额更值得关注的是查处方式：eSocial会将企业申报的内容与INSS、联邦税务局和劳动部的数据库进行比对，并即时指出不一致之处。",
 "ocupacionais": "职业健康体检",
 "on-line, no seu ritmo": "线上学习，自主安排节奏",
 "ou fale com o nosso comercial.": "或与我们的商务团队联系。",
 "para a clínica falar com você": "便于诊所与您联系",
 "para a sua": "为您的",
 "pelo menos 6 caracteres": "至少6个字符",
 "pendente": "待处理",
 "pesquisa sangue oculto nas fezes, é menos invasivo e pode ser repetido com mais frequência. Resultados alterados costumam ser investigados com colonoscopia.": "检测粪便隐血，创伤更小，可以更频繁地重复进行。结果异常时通常需要进一步做结肠镜检查。",
 "precisaram se afastar por motivo de saúde em 2025 no Brasil — o maior volume desde 2021, cerca de 15% acima do ano anterior. O dado muda a conta de qualquer empresa que ainda trate o exame periódico como formalidade.": "名劳动者在2025年因健康原因需要休假——这是自2021年以来的最高数字，比上一年增长约15%。这一数据改变了任何仍把定期体检当作走形式的企业的成本账。",
 "quando há alteração de risco;": "当风险发生变化时；",
 "que realiza, e cuida para que tudo seja entregue": "并确保一切都能",
 "registro da exposição a agentes nocivos (ruído, químicos, etc.), com base no PGR e no LTCAT.": "以PGR和LTCAT为依据，记录劳动者接触有害因素（噪声、化学品等）的情况。",
 "registro de acidentes e doenças ocupacionais dentro do prazo legal.": "在法定期限内登记事故和职业病。",
 "riscos psicossociais": "社会心理风险",
 "saúde ocupacional, segurança do trabalho e cuidado clínico": "职业健康、劳动安全与临床诊疗",
 "segunda a sexta-feira, das 7h às 18h; aos sábados, das 7h às 12h.": "周一至周五7:00-18:00；周六7:00-12:00。",
 "seu login": "您的登录名",
 "transtornos mentais": "精神障碍",
 "treinamentos": "门培训课程",
 "© 2026 Clínica Medicina Humana. Todos os direitos reservados.": "© 2026 Clínica Medicina Humana。版权所有。",
 "Área Médica": "医师专区",
 "Área de interesse*": "意向领域*",
 "Área do Aluno": "学员专区",
 "Área do aluno": "学员专区",
 "Áreas em que você pode atuar": "您可以任职的岗位领域",
 "Último ano": "最近一年",
 "Últimos 3 meses": "最近3个月",
 "Últimos 30 dias": "最近30天",
 "Últimos 6 meses": "最近6个月",
 "Últimos pendentes de liberação": "最新待发布项",
 "é feito no encerramento do contrato, registrando as condições de saúde do colaborador no desligamento — uma proteção importante para a empresa e para o trabalhador.": "则在合同终止时进行，记录员工离职时的健康状况——这对企业和劳动者都是一项重要的保障。",
 "é o documento emitido pelo médico do trabalho que atesta se o colaborador está apto ou inapto para a função. Ele é obrigatório em diferentes momentos:": "是由职业医师出具的文件，证明员工是否适合从事该岗位。它在多个时点都是强制性的：",
 "é o documento que atesta a aptidão do colaborador — obrigatório nos exames admissional, periódico, de retorno ao trabalho, de mudança de função e demissional.": "是证明员工岗位适任性的文件——入职、定期、复工、岗位变更和离职体检均须出具。",
 "é o documento que materializa esse processo, com o inventário de riscos e o plano de ação, e substituiu o antigo PPRA.": "是将这一过程具体落实的文件，包含风险清单和行动计划，并取代了原来的PPRA。",
 "é o documento que materializa esse processo, reunindo o inventário de riscos e o plano de ação. O PGR substituiu o antigo PPRA e passou a ter uma visão mais ampla e integrada da prevenção.": "是将这一过程具体落实的文件，汇集了风险清单和行动计划。PGR取代了原来的PPRA，对预防工作有了更全面、更整合的视角。",
 "é o processo de gestão dos riscos. Já o": "是风险管理的过程。而",
 "é o sistema do Governo Federal que unifica o envio das informações trabalhistas, previdenciárias e fiscais das empresas. No módulo de": "是巴西联邦政府统一报送企业劳动、社保和税务信息的系统。在",
 "— como estresse ocupacional, assédio e sobrecarga — entre os fatores a serem identificados e gerenciados. Isso reforça que a saúde mental no trabalho também é responsabilidade da empresa.": "——例如职业压力、职场骚扰和超负荷——纳入需要识别和管理的因素。这进一步表明，职场心理健康同样是企业的责任。",
 "— mantendo a sua empresa sempre em conformidade e livre de autuações.": "——让贵公司始终保持合规，远离处罚。",
 "— o processo contínuo de identificar, avaliar e controlar os riscos. O": "——即持续识别、评估和控制风险的过程。而",
 "“Cuidando de você em cada detalhe.”": "“在每一个细节中关爱您。”",
 "← Cursos": "← 课程",
 "← Voltar para a página inicial": "← 返回首页",
 "← Voltar para as noticias": "← 返回新闻列表",
 "← Voltar para as notícias": "← 返回新闻列表",
 "← Voltar para o login": "← 返回登录页"
};
