-- =====================================================================
--  HOMOLOGAÇÃO: O CADASTRO DE COLABORADORES DE CADA EMPRESA
--
--  Rode no SQL Editor do Supabase DEPOIS do 02-cpf-e-historico.sql. Pode
--  rodar de novo: tudo aqui é "if not exists" ou "create or replace", e
--  nada é apagado.
--
--  O QUE MUDA NO DIA A DIA
--  -----------------------
--  Hoje o RH digita o CPF e o nome a cada atestado, e a tela puxa o nome
--  de um atestado anterior quando já existe. Funciona, mas o primeiro
--  atestado de cada pessoa ainda é digitado, e é nele que nascem o nome
--  em três grafias e o CPF de quem não tem o documento à mão.
--
--  Com o cadastro, a clínica sobe a lista de colaboradores da empresa
--  (pelo módulo Homologação do SistemaCMH, inclusive importando de uma
--  planilha), e no site o RH PROCURA a pessoa, anexa o atestado e envia.
--  Nome, matrícula e filial saem do cadastro, e não do teclado.
--
--  O CPF É A CHAVE, a matrícula é um campo a mais: é a mesma decisão do
--  02-cpf-e-historico.sql, e pela mesma razão (o CPF é da pessoa, tem
--  dígito para conferir e sobrevive à troca de empresa).
--
--  QUEM MEXE
--    clínica (equipe com o módulo Homologação) -> cadastra, corrige,
--      importa e desliga
--    RH da empresa -> só LÊ os da empresa dele, para escolher
--    médico -> não precisa: o processo já leva CPF e nome gravados
--
--  EMPRESA SEM NINGUÉM CADASTRADO CONTINUA COMO HOJE, com o RH digitando.
--  Ninguém fica parado esperando a clínica subir a folha inteira.
-- =====================================================================

create table if not exists public.homol_colaborador (
  id            bigint generated by default as identity primary key,
  empresa_cnpj  text not null check (empresa_cnpj ~ '^\d{14}$'),
  -- só os 11 dígitos, como no homol_processo.cpf: máscara é coisa de tela
  cpf           text not null check (cpf ~ '^\d{11}$'),
  nome          text not null check (length(btrim(nome)) between 3 and 160),
  matricula     text,
  filial        text,
  cargo         text,
  ativo         boolean not null default true,
  criado_por    text,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  -- a mesma pessoa pode trabalhar em duas empresas clientes, e cada uma
  -- tem a sua linha; o que não pode é repetir dentro da mesma empresa
  unique (empresa_cnpj, cpf)
);
create index if not exists idx_homol_colab_cnpj on public.homol_colaborador (empresa_cnpj, ativo);
create index if not exists idx_homol_colab_nome on public.homol_colaborador (empresa_cnpj, nome);
alter table public.homol_colaborador enable row level security;

-- ler: o RH, os da empresa dele; o médico e a equipe, todos
drop policy if exists homol_colab_ler on public.homol_colaborador;
create policy homol_colab_ler on public.homol_colaborador
  for select using (
    empresa_cnpj = public.homol_meu_cnpj()
    or public.homol_eh_medico()
    or public.homol_is_equipe());

-- escrever: só a clínica, pelo SistemaCMH. Colaborador não se apaga:
-- desliga (ativo = false), senão os atestados dele ficariam ligados a um
-- cadastro que sumiu.
drop policy if exists homol_colab_equipe_ins on public.homol_colaborador;
create policy homol_colab_equipe_ins on public.homol_colaborador
  for insert with check (public.homol_is_equipe());
drop policy if exists homol_colab_equipe_upd on public.homol_colaborador;
create policy homol_colab_equipe_upd on public.homol_colaborador
  for update using (public.homol_is_equipe()) with check (public.homol_is_equipe());

create or replace function public.homol_colab_carimbo()
returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.cpf           := regexp_replace(coalesce(new.cpf, ''), '\D', '', 'g');
  new.nome          := upper(btrim(new.nome));
  new.matricula     := nullif(btrim(coalesce(new.matricula, '')), '');
  new.filial        := nullif(btrim(coalesce(new.filial, '')), '');
  new.cargo         := nullif(btrim(coalesce(new.cargo, '')), '');
  new.atualizado_em := now();
  if tg_op = 'INSERT' then
    new.criado_por := coalesce(new.criado_por, public.homol_meu_nome());
    new.criado_em  := now();
  else
    -- colaborador não muda de empresa nem de CPF: para corrigir um CPF
    -- errado, desliga-se a linha errada e cadastra-se a certa, e assim
    -- fica claro no cadastro o que aconteceu
    new.empresa_cnpj := old.empresa_cnpj;
    new.cpf          := old.cpf;
    new.criado_por   := old.criado_por;
    new.criado_em    := old.criado_em;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_homol_colab_carimbo on public.homol_colaborador;
create trigger trg_homol_colab_carimbo before insert or update on public.homol_colaborador
  for each row execute function public.homol_colab_carimbo();


-- =====================================================================
--  O PROCESSO PASSA A SAIR DO CADASTRO, quando a empresa tem cadastro
--
--  GATILHO SEPARADO, de propósito: o homol_processo_regras continua
--  sendo o do 02, com o parecer, as filiais e o resto. Este roda ANTES
--  dele (o Postgres dispara os gatilhos de mesmo tipo em ordem
--  alfabética, e "colaborador" vem antes de "regras"), carimba nome,
--  matrícula e filial a partir do cadastro, e sai. Assim, mexer num não
--  obriga a reescrever o outro.
-- =====================================================================
create or replace function public.homol_processo_do_cadastro()
returns trigger
language plpgsql security definer set search_path = public as $$
declare
  cnpj  text := public.homol_meu_cnpj();
  colab public.homol_colaborador;
begin
  -- médico e equipe não passam por aqui: quem lança é o RH
  if cnpj is null then
    return new;
  end if;
  if not exists (select 1 from public.homol_colaborador c
                  where c.empresa_cnpj = cnpj and c.ativo) then
    return new;                      -- empresa ainda sem cadastro
  end if;

  select * into colab from public.homol_colaborador c
   where c.empresa_cnpj = cnpj and c.ativo
     and c.cpf = regexp_replace(coalesce(new.cpf, ''), '\D', '', 'g');
  if colab.id is null then
    raise exception 'COLABORADOR_NAO_CADASTRADO: escolha um colaborador da lista da sua empresa, ou peça à clínica para cadastrá-lo';
  end if;

  new.cpf    := colab.cpf;
  new.nome   := colab.nome;
  new.chapa  := coalesce(colab.matricula, new.chapa);
  new.filial := coalesce(colab.filial, new.filial);
  return new;
end;
$$;
drop trigger if exists trg_homol_processo_colaborador on public.homol_processo;
create trigger trg_homol_processo_colaborador
  before insert or update on public.homol_processo
  for each row execute function public.homol_processo_do_cadastro();


-- =====================================================================
--  Permissões
-- =====================================================================
revoke all on public.homol_colaborador from anon;
grant select, insert, update on public.homol_colaborador to authenticated;


-- =====================================================================
--  Confira: a coluna "achei" tem de bater com a "esperado"
-- =====================================================================
select 'tabela de colaboradores' as o_que,
       (select count(*) from information_schema.tables
         where table_schema = 'public' and table_name = 'homol_colaborador')::text as achei,
       '1' as esperado
union all
select 'RLS ligada',
       (select c.relrowsecurity::text from pg_class c join pg_namespace n on n.oid = c.relnamespace
         where n.nspname = 'public' and c.relname = 'homol_colaborador'), 'true'
union all
select 'politicas do cadastro',
       (select count(*)::text from pg_policies
         where schemaname = 'public' and tablename = 'homol_colaborador'), '3'
union all
select 'gatilho do cadastro no processo',
       (select count(*)::text from pg_trigger t join pg_class c on c.oid = t.tgrelid
         where c.relname = 'homol_processo' and t.tgname = 'trg_homol_processo_colaborador'), '1'
union all
select 'o gatilho do cadastro dispara ANTES do de regras',
       (select (min(tgname) = 'trg_homol_processo_colaborador')::text
          from pg_trigger t join pg_class c on c.oid = t.tgrelid
         where c.relname = 'homol_processo' and not t.tgisinternal
           and tgname like 'trg_homol_processo_%'), 'true'
union all
select 'anon NAO le colaboradores',
       (not has_table_privilege('anon', 'public.homol_colaborador', 'select'))::text, 'true';
